import test from 'node:test';import assert from 'node:assert/strict';
import {MESH_FORMAT,gridMesh,validateMeshProject,meshPositions,bindPreset} from '../../v2/mesh-project.js';
import {readPSDLayers} from '../../v2/psd-layers.js';
const png='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQIHWP4z8DwHwAFgAI/ScLbtAAAAABJRU5ErkJggg==';
const make=()=>({format:MESH_FORMAT,version:1,name:'fixture',width:10,height:20,parameters:[{id:'ParamBreath',name:'呼吸',min:0,max:1,default:0}],layers:[{id:'body',name:'body',width:1,height:1,texture:png,visible:true,opacity:1,mesh:gridMesh(0,0,10,20,2),bindings:{}}]});
test('actual keyform interpolation survives JSON save/reopen without mutating rest vertices',()=>{const p=make(),l=p.layers[0],base=l.mesh.positions.slice();bindPreset(l,'ParamBreath','breath',.1);const a=meshPositions(l,{ParamBreath:0}),b=meshPositions(l,{ParamBreath:1}),middle=meshPositions(l,{ParamBreath:.5});assert.deepEqual(a,base);assert.notDeepEqual(b,a);for(let i=0;i<a.length;i++)assert.equal(middle[i],(a[i]+b[i])/2);const reopened=validateMeshProject(JSON.parse(JSON.stringify(p)));assert.deepEqual(meshPositions(reopened.layers[0],{ParamBreath:1}),b);assert.deepEqual(l.mesh.positions,base);});
test('project rejects network textures, mismatched keys, impossible indices and invalid image dimensions',()=>{const p=make();p.layers[0].texture='https://untrusted.invalid/a.png';assert.throws(()=>validateMeshProject(p),/PNG/);const q=make();q.layers[0].mesh.indices[0]=99;assert.throws(()=>validateMeshProject(q),/索引/);const r=make();bindPreset(r.layers[0],'ParamBreath','breath');r.layers[0].bindings.ParamBreath[1].positions.pop();assert.throws(()=>validateMeshProject(r),/端点/);const s=make();s.layers[0].width=4000;assert.throws(()=>validateMeshProject(s),/尺寸/);});
function fixture(compression=0){const u16=n=>{const b=Buffer.alloc(2);b.writeUInt16BE(n);return b;},i16=n=>{const b=Buffer.alloc(2);b.writeInt16BE(n);return b;},u32=n=>{const b=Buffer.alloc(4);b.writeUInt32BE(n);return b;},i32=n=>{const b=Buffer.alloc(4);b.writeInt32BE(n);return b;};const plane=Buffer.concat([u16(compression),...(compression===0?[Buffer.from([20,30])]:[u16(3),Buffer.from([1,20,30])])]),name=Buffer.from([1,65,0,0]),extra=Buffer.concat([u32(0),u32(0),name]);const record=Buffer.concat([i32(0),i32(0),i32(1),i32(2),u16(4),...[-1,0,1,2].map(id=>Buffer.concat([i16(id),u32(plane.length)])),Buffer.from('8BIMnorm'),Buffer.from([255,0,0,0]),u32(extra.length),extra]);const info=Buffer.concat([i16(1),record,...[0,1,2,3].map(()=>plane)]),section=Buffer.concat([u32(info.length),info]);return Buffer.concat([Buffer.from('8BPS'),u16(1),Buffer.alloc(6),u16(4),u32(1),u32(2),u16(8),u16(3),u32(0),u32(0),u32(section.length),section]);}
test('PSD raw and PackBits decode exact pixels; corrupt/truncated sources fail before rendering',()=>{for(const c of [0,1]){const p=readPSDLayers(fixture(c));assert.equal(p.layers.length,1);assert.deepEqual([...p.layers[0].rgba],[20,20,20,20,30,30,30,30]);}assert.throws(()=>readPSDLayers(fixture().subarray(0,35)),/截断/);const bad=fixture(1);bad[bad.length-3]=4;assert.throws(()=>readPSDLayers(bad),/截断|RLE/);});
