import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {planMoc3,planAtlas,writerInput,testMotion,modelReferences} from '../moc3-plan.js';
import {gridMesh} from '../../v2/mesh-project.js?ui=3';
const png=Buffer.from(JSON.parse(readFileSync(new URL('../spec/moc3-synthetic.mesh2d.json',import.meta.url),'utf8')).layers[0].texture.split(',')[1],'base64');
function fixture(){const mesh=gridMesh(0,0,256,256,1);return {format:'studio-mesh2d',version:1,name:'Synthetic adapter fixture',width:256,height:256,parameters:[{id:'ParamDemo',min:0,max:1,default:0}],layers:[{id:'synthetic',width:256,height:256,texture:'data:image/png;base64,'+png.toString('base64'),visible:true,opacity:1,mesh,bindings:{ParamDemo:[{value:0,positions:[...mesh.positions]},{value:1,positions:mesh.positions.map((v,i)=>i===1?v+20:v)}]}}]};}
test('one moving parameter produces a flat two-keyform writer plan without executing writer',()=>{const plan=planMoc3(fixture(),'ParamDemo'),atlas=planAtlas(plan),input=writerInput(plan,atlas);assert.equal(atlas.size,512);assert.equal(input.project.nodes[0].moc3Keyforms[1][0].y,20);assert.deepEqual(input.project.nodes[0].mesh.triangles,[[0,1,2],[1,3,2]]);assert.equal(input.regions.get('synthetic').atlasIndex,0);assert.equal(testMotion(plan).Curves[0].Id,'ParamDemo');assert.equal(modelReferences().FileReferences.Moc,'model.moc3');});
test('independent second moving parameter is rejected rather than silently flattened',()=>{const raw=fixture();raw.parameters.push({id:'ParamOther',min:0,max:1,default:0});raw.layers[0].bindings.ParamOther=structuredClone(raw.layers[0].bindings.ParamDemo);assert.throws(()=>planMoc3(raw,'ParamDemo'),/多参数组合/);});
test('rotation, parent links, mask and physics metadata are rejected before canonicalization',()=>{for(const field of ['rotation','parentId','pivot','mask','physics']){const raw=fixture();raw.layers[0][field]={};assert.throws(()=>planMoc3(raw,'ParamDemo'),/未支持字段/);}});
test('legacy eye keyforms, default and motion map together to standard open01',()=>{const raw=fixture();raw.parameters[0].id='ParamEyeLOpen';raw.layers[0].bindings.ParamEyeLOpen=raw.layers[0].bindings.ParamDemo;delete raw.layers[0].bindings.ParamDemo;const plan=planMoc3(raw,'ParamEyeLOpen');assert.equal(plan.parameter.default,1);assert.equal(plan.meshes[0].frames[0][1],20);assert.equal(plan.meshes[0].frames[1][1],0);assert.deepEqual(testMotion(plan).Curves[0].Segments,[0,1,0,1.5,0,0,3,1]);});
test('explicit modern eye-open semantics are retained',()=>{const raw=fixture();raw.parameters[0]={id:'ParamEyeROpen',min:0,max:1,default:1,semantics:'eye-open-01'};raw.layers[0].bindings.ParamEyeROpen=raw.layers[0].bindings.ParamDemo;delete raw.layers[0].bindings.ParamDemo;const plan=planMoc3(raw,'ParamEyeROpen');assert.equal(plan.mapping.legacyEyeReversed,false);assert.equal(plan.meshes[0].frames[0][1],0);});
test('oversized cropped texture cannot lose pixels to fit the atlas',()=>{const plan=planMoc3(fixture(),'ParamDemo');plan.meshes[0].width=4096;assert.throws(()=>planAtlas(plan),/不会缩图或裁掉/);});
test('hidden-only animation is rejected',()=>{const raw=fixture();raw.layers[0].visible=false;assert.throws(()=>planMoc3(raw,'ParamDemo'),/可见图层/);});
test('flat layers are reversed for the fixed writer/Core tie order to preserve source compositing',()=>{const raw=fixture(),front=structuredClone(raw.layers[0]);front.id='front';front.bindings={};raw.layers.push(front);const plan=planMoc3(raw,'ParamDemo');assert.deepEqual(plan.meshes.map(m=>m.id),['front','synthetic']);assert.deepEqual(writerInput(plan,planAtlas(plan)).project.nodes.map(m=>m.draw_order),[2,1]);});
