// No network, installs, host agents, credentials or uploaded executable inputs.
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {fileURLToPath} from 'node:url';
import {gridMesh,bindPreset,validateMeshProject} from '../v2/mesh-project.js';
import {MATERIAL_ROLES} from '../v2/material-contract.js';
import {planMoc3,planAtlas,writerInput,modelReferences,testMotion} from '../studio/moc3-plan.js';
import {decodePNG,atlasPNG} from './png.mjs';
import {zip} from './zip.mjs';
const root=fileURLToPath(new URL('../',import.meta.url)),sha=b=>crypto.createHash('sha256').update(b).digest('hex'),json=v=>JSON.stringify(v,null,2)+'\n';
const read=file=>{const b=fs.readFileSync(file);if(b.length>64*1024*1024)throw new Error('Input exceeds 64 MiB');return b;};
const fresh=dir=>{if(fs.existsSync(dir))throw new Error('Output already exists; choose a fresh directory');fs.mkdirSync(dir,{recursive:true});};
const fields=(o,allowed)=>{if(!o||typeof o!=='object'||Array.isArray(o)||Object.keys(o).some(k=>!allowed.includes(k)))throw new Error('Unsupported manifest field; do not silently discard source structure');};
const project=file=>{const bytes=read(file),raw=JSON.parse(bytes);validateMeshProject(raw);return {raw,bytes};};
function writeSource(out,raw,bytes,license){const files=new Map([['project.mesh2d.json',bytes],['ASSET-LICENSE.txt',Buffer.from(license)]]);const manifest={format:'studio-editable-project',version:1,projectEntry:'project.mesh2d.json',runtimeIncluded:false,files:Object.fromEntries([...files].map(([p,b])=>[p,{bytes:b.length,sha256:sha(b)}]))};files.set('project.manifest.json',Buffer.from(json(manifest)));for(const [p,b]of files)fs.writeFileSync(path.join(out,p),b);fs.writeFileSync(path.join(out,'editable-project.zip'),zip(files));return manifest;}
async function main(){const [command,input,out,arg]=process.argv.slice(2);if(command==='inspect'){const {raw,bytes}=project(input);const effective=[...new Set(raw.layers.flatMap(l=>Object.entries(l.bindings||{}).filter(([,k])=>k[0].positions.some((v,i)=>Math.abs(v-k[1].positions[i])>1e-7)).map(([id])=>id)))];let support;try{support=planMoc3(raw,arg||effective[0]).warnings;}catch(e){support={blocked:e.message};}console.log(json({sha256:sha(bytes),layers:raw.layers.length,vertices:raw.layers.reduce((n,l)=>n+l.mesh.positions.length/2,0),movingParameters:effective,exportSupport:support}));return;}
  if(command==='source'){const {raw,bytes}=project(input);const license=arg?read(arg).toString():'Asset rights are not declared. Local evaluation only; do not redistribute.';fresh(out);console.log(json(writeSource(out,raw,bytes,license)));return;}
  if(command==='materials'){const manifest=JSON.parse(read(input));fields(manifest,['format','version','name','width','height','license','parameters','layers']);for(const p of manifest.parameters||[])fields(p,['id','name','min','max','default','semantics']);const base=path.dirname(fs.realpathSync(input));if(manifest.format!=='studio-png-layers'||manifest.version!==1||!Array.isArray(manifest.layers)||!manifest.layers.length||manifest.layers.length>16||typeof manifest.license!=='string'||!manifest.license.length||manifest.license.length>8000)throw new Error('Expected PNG layers manifest v1 and asset rights statement');const raw={format:'studio-mesh2d',version:1,name:manifest.name||'Local character',width:manifest.width,height:manifest.height,parameters:manifest.parameters,layers:[]};for(const layer of manifest.layers){fields(layer,['id','name','file','sha256','left','top','role','opacity','bind']);if(layer.bind)fields(layer.bind,['parameterId','kind','strength']);if(typeof layer.file!=='string'||path.isAbsolute(layer.file)||layer.file.split(/[\\/]/).some(p=>!p||p==='.'||p==='..')||!layer.file.endsWith('.png'))throw new Error('Layer path must be a relative PNG');const file=fs.realpathSync(path.join(base,layer.file));if(!file.startsWith(base+path.sep))throw new Error('Layer escapes manifest directory');const bytes=read(file);if(sha(bytes)!==layer.sha256)throw new Error('Layer hash mismatch: '+layer.file);const image=decodePNG(bytes);if(!Number.isFinite(layer.left)||!Number.isFinite(layer.top)||!MATERIAL_ROLES.includes(layer.role))throw new Error('Layer offset/role missing');const l={id:layer.id,name:layer.name,width:image.width,height:image.height,texture:'data:image/png;base64,'+bytes.toString('base64'),visible:true,opacity:layer.opacity??1,mesh:gridMesh(layer.left,layer.top,image.width,image.height,8),bindings:{},role:layer.role,roleSource:'manifest',occlusionComplete:false};if(layer.bind){const b=layer.bind,p=raw.parameters.find(p=>p.id===b.parameterId);if(!p||!['breath','blink','mouth','sway'].includes(b.kind)||!Number.isFinite(b.strength)||b.strength<0||b.strength>.1)throw new Error('Invalid starter binding');bindPreset(l,p.id,b.kind,b.strength,{semantics:p.semantics});}raw.layers.push(l);}validateMeshProject(raw);fresh(out);fs.writeFileSync(path.join(out,'materials.input.json'),json(manifest));console.log(json(writeSource(out,raw,Buffer.from(json(raw)),manifest.license)));return;}
  if(command==='export'){const {raw,bytes}=project(input),plan=planMoc3(raw,arg),atlas=planAtlas(plan),provenance=JSON.parse(read(path.join(root,'PROVENANCE.json'))),writer=path.join(root,'vendor/experimental-moc3/moc3writer.js');if(sha(read(writer))!==provenance.writerSHA256)throw new Error('Pinned writer hash mismatch');const png=atlasPNG(plan,atlas);const {generateMoc3}=await import('../vendor/experimental-moc3/moc3writer.js');const binary=Buffer.from(generateMoc3(writerInput(plan,atlas)));if(binary.length<1984||binary.length>8*1024*1024||binary.toString('ascii',0,4)!=='MOC3')throw new Error('Writer output outside bounds');const files=new Map([['model.moc3',binary],['model.model3.json',Buffer.from(json(modelReferences()))],['textures/texture_00.png',png],['motions/test.motion3.json',Buffer.from(json(testMotion(plan)))],['WRITER-LICENSE.txt',read(path.join(root,'vendor/experimental-moc3/LICENSE.MIT'))]]);const validation={format:'studio-runtime-validation',version:1,status:'candidate-core-and-visual-validation-pending',sourceSHA256:sha(bytes),writerSHA256:provenance.writerSHA256,coreIncluded:false,support:plan.warnings,files:Object.fromEntries([...files].map(([p,b])=>[p,{bytes:b.length,sha256:sha(b)}]))};files.set('VALIDATION.json',Buffer.from(json(validation)));files.set('README.txt',Buffer.from('Candidate flat mesh runtime pack. Core acceptance, actual texture pixels and motion playback still require verification. No asset redistribution rights are granted. Keep the editable source separately.\n'));fresh(out);for(const [p,b]of files){fs.mkdirSync(path.dirname(path.join(out,p)),{recursive:true});fs.writeFileSync(path.join(out,p),b);}fs.writeFileSync(path.join(out,'candidate-model.zip'),zip(files));console.log(json(validation));return;}
  throw new Error('Usage: node scripts/cli.mjs inspect PROJECT | source PROJECT NEW_DIR [ASSET_LICENSE] | materials MANIFEST NEW_DIR | export PROJECT NEW_DIR PARAMETER_ID');}
main().catch(e=>{console.error(e.message);process.exitCode=1;});
