// Bounded PNG codec: 8-bit RGB/RGBA, non-interlaced. Node built-ins only.
import {inflateSync,deflateSync} from 'node:zlib';
const signature=Buffer.from([137,80,78,71,13,10,26,10]);
const table=Uint32Array.from({length:256},(_,n)=>{for(let i=0;i<8;i++)n=n&1?0xedb88320^(n>>>1):n>>>1;return n>>>0;});
export function crc32(bytes){let n=0xffffffff;for(const b of bytes)n=table[(n^b)&255]^(n>>>8);return (n^0xffffffff)>>>0;}
const check=(ok,message)=>{if(!ok)throw new Error(message);};
export function decodePNG(input){const b=Buffer.from(input);check(b.length<=32*1024*1024&&b.subarray(0,8).equals(signature),'Invalid or oversized PNG');let p=8,w,h,channels,idat=[],ended=false,header=false;
  while(p<b.length){check(p+12<=b.length,'Truncated PNG');const n=b.readUInt32BE(p),type=b.toString('ascii',p+4,p+8);check(n<=32*1024*1024&&p+12+n<=b.length,'Invalid PNG chunk');const data=b.subarray(p+8,p+8+n);check(crc32(b.subarray(p+4,p+8+n))===b.readUInt32BE(p+8+n),'PNG CRC mismatch');
    if(type==='IHDR'){check(!header&&p===8&&n===13,'Invalid IHDR');header=true;w=data.readUInt32BE(0);h=data.readUInt32BE(4);channels=data[9]===6?4:data[9]===2?3:0;check(w>0&&h>0&&w<=4096&&h<=4096&&w*h<=16*1024*1024&&data[8]===8&&channels&&data[10]===0&&data[11]===0&&data[12]===0,'Only bounded 8-bit RGB/RGBA non-interlaced PNG is supported');}
    else if(type==='IDAT'){check(header&&!ended,'Invalid IDAT');idat.push(data);}else if(type==='IEND'){check(n===0&&idat.length>0,'Invalid IEND');ended=true;p+=12;break;}else if(type==='acTL'||type==='tRNS'||type[0]===type[0].toUpperCase())throw new Error('Unsupported PNG critical chunk or transparency: '+type);p+=12+n;
  }check(ended&&p===b.length,'Incomplete PNG or trailing bytes');const stride=w*channels,expected=(stride+1)*h,raw=inflateSync(Buffer.concat(idat),{maxOutputLength:expected});check(raw.length===expected,'PNG inflated length mismatch');const pixels=new Uint8Array(w*h*4),previous=new Uint8Array(stride);
  const paeth=(a,b,c)=>{const p=a+b-c,pa=Math.abs(p-a),pb=Math.abs(p-b),pc=Math.abs(p-c);return pa<=pb&&pa<=pc?a:pb<=pc?b:c;};
  for(let y=0;y<h;y++){const filter=raw[y*(stride+1)],row=new Uint8Array(stride);check(filter<=4,'Unsupported PNG filter');for(let x=0;x<stride;x++){const a=x>=channels?row[x-channels]:0,z=previous[x],c=x>=channels?previous[x-channels]:0;row[x]=(raw[y*(stride+1)+1+x]+[0,a,z,Math.floor((a+z)/2),paeth(a,z,c)][filter])&255;}for(let x=0;x<w;x++){const at=(y*w+x)*4;pixels.set(row.subarray(x*channels,x*channels+3),at);pixels[at+3]=channels===4?row[x*4+3]:255;}previous.set(row);}return {width:w,height:h,pixels};
}
export function encodePNG(width,height,pixels){check(Number.isInteger(width)&&Number.isInteger(height)&&width>0&&height>0&&width<=4096&&height<=4096&&pixels.length===width*height*4,'Invalid RGBA output');const chunk=(type,data)=>{const t=Buffer.from(type),o=Buffer.alloc(data.length+12);o.writeUInt32BE(data.length);t.copy(o,4);Buffer.from(data).copy(o,8);o.writeUInt32BE(crc32(o.subarray(4,8+data.length)),8+data.length);return o;};const header=Buffer.alloc(13);header.writeUInt32BE(width);header.writeUInt32BE(height,4);header[8]=8;header[9]=6;const raw=Buffer.alloc((width*4+1)*height);for(let y=0;y<height;y++)Buffer.from(pixels.buffer,pixels.byteOffset+y*width*4,width*4).copy(raw,y*(width*4+1)+1);return Buffer.concat([signature,chunk('IHDR',header),chunk('IDAT',deflateSync(raw,{level:9})),chunk('IEND',Buffer.alloc(0))]);}
export function atlasPNG(plan,atlas){const rgba=new Uint8Array(atlas.size**2*4);for(const entry of atlas.entries){const mesh=plan.meshes.find(m=>m.id===entry.id),image=decodePNG(Buffer.from(mesh.texture.split(',')[1],'base64'));check(image.width===entry.width&&image.height===entry.height,'Texture dimensions mismatch');for(let y=-2;y<entry.height+2;y++)for(let x=-2;x<entry.width+2;x++){const sx=Math.max(0,Math.min(entry.width-1,x)),sy=Math.max(0,Math.min(entry.height-1,y));rgba.set(image.pixels.subarray((sy*entry.width+sx)*4,(sy*entry.width+sx)*4+4),((entry.y+y)*atlas.size+entry.x+x)*4);}}return encodePNG(atlas.size,atlas.size,rgba);}
