// Executes only a user-supplied official Core matching the pinned vendor hash.
import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import vm from 'node:vm';import {createRequire} from 'node:module';
import {planMoc3,planAtlas} from '../studio/moc3-plan.js';import {decodePNG} from './png.mjs';
const [source,runtimeDir,parameterId,coreFile,reportFile]=process.argv.slice(2),sha=b=>crypto.createHash('sha256').update(b).digest('hex');
const assert=(ok,m)=>{if(!ok)throw new Error(m);};let model,moc;
try{assert(source&&runtimeDir&&parameterId&&coreFile&&reportFile,'Usage: node scripts/verify-core.mjs PROJECT RUNTIME_DIR PARAMETER_ID OFFICIAL_CORE_FILE NEW_REPORT_FILE');assert(!fs.existsSync(reportFile),'Report already exists');const provenance=JSON.parse(fs.readFileSync(new URL('../PROVENANCE.json',import.meta.url))),coreBytes=fs.readFileSync(coreFile);assert(sha(coreBytes)===provenance.core.sha256,'Official Core hash mismatch; arbitrary JS is rejected');const sourceBytes=fs.readFileSync(source),raw=JSON.parse(sourceBytes),plan=planMoc3(raw,parameterId),atlas=planAtlas(plan),validation=JSON.parse(fs.readFileSync(path.join(runtimeDir,'VALIDATION.json')));assert(validation.sourceSHA256===sha(sourceBytes),'Source identity mismatch');for(const [p,record]of Object.entries(validation.files)){assert(/^[A-Za-z0-9_./-]+$/.test(p)&&!p.startsWith('/')&&!p.split('/').some(s=>!s||s==='.'||s==='..'),'Unsafe resource path');const b=fs.readFileSync(path.join(runtimeDir,p));assert(b.length===record.bytes&&sha(b)===record.sha256,'Resource hash mismatch: '+p);}const texture=decodePNG(fs.readFileSync(path.join(runtimeDir,'textures/texture_00.png')));assert(texture.width===atlas.size&&texture.height===atlas.size,'Atlas dimensions mismatch');
  const context={atob,console:{log(){},warn(){},error(){},assert(){}},WebAssembly,ArrayBuffer,Uint8Array,Int8Array,Uint16Array,Int16Array,Uint32Array,Int32Array,Float32Array,Float64Array,Math,setTimeout,clearTimeout,TextDecoder,process,require:createRequire(import.meta.url),__dirname:path.dirname(path.resolve(coreFile))};vm.createContext(context);vm.runInContext(coreBytes.toString(),context,{filename:coreFile,timeout:5000});const core=context.Live2DCubismCore;for(let i=0;;i++){try{core.Version.csmGetVersion();break;}catch(e){if(i===100)throw e;await new Promise(r=>setTimeout(r,20));}}const b=fs.readFileSync(path.join(runtimeDir,'model.moc3')),binary=b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength);assert(core.Moc.prototype.hasMocConsistency(binary)===1,'Core consistency rejected');moc=core.Moc.fromArrayBuffer(binary);model=core.Model.fromMoc(moc);assert(model,'Core model load failed');assert(model.parameters.count===1&&model.parameters.ids[0]===parameterId,'Parameter mismatch');assert(model.parameters.minimumValues[0]===0&&model.parameters.maximumValues[0]===1&&Math.abs(model.parameters.defaultValues[0]-plan.parameter.default)<1e-6,'Parameter bounds/default mismatch');assert(model.drawables.count===plan.meshes.length,'Drawable count mismatch');model.update();
  const report={format:'studio-core-validation',version:1,status:'core-and-source-vertices-passed-visual-motion-playback-pending',sourceSHA256:sha(sourceBytes),mocSHA256:sha(b),coreSHA256:sha(coreBytes),coreVersion:core.Version.csmGetVersion(),consistency:1,meshes:[],samples:[],browserAcceptance:'PENDING: actual texture pixels, source comparison, motion playback and explicit visual review'};
  for(const [i,mesh]of plan.meshes.entries()){const entry=atlas.entries.find(e=>e.id===mesh.id),d=model.drawables;assert(d.vertexCounts[i]===mesh.frames[0].length/2&&d.indices[i].length===mesh.indices.length,'Mesh topology mismatch');assert(d.textureIndices[i]===0&&Math.abs(d.opacities[i]-mesh.opacity)<1e-5&&model.renderOrders[i]===plan.meshes.length-1-i,'Texture/opacity/layer order mismatch');const indices=mesh.indices.flatMap((_,j)=>j%3===0?[mesh.indices[j+2],mesh.indices[j+1],mesh.indices[j]]:[]);assert(indices.every((v,j)=>v===d.indices[i][j]),'Triangle index mismatch');const uvError=Math.max(...mesh.uvs.map((v,j)=>Math.abs((j%2?1-(entry.y+v*mesh.height)/atlas.size:(entry.x+v*mesh.width)/atlas.size)-d.vertexUvs[i][j])));assert(uvError<1e-5,'UV mismatch');report.meshes.push({id:mesh.id,vertices:d.vertexCounts[i],triangles:d.indices[i].length/3,renderOrder:model.renderOrders[i],uvError});}
  const ppu=Math.max(plan.width,plan.height);for(const value of [plan.parameter.default,0,.5,1,0]){model.parameters.values[0]=value;model.update();let maxError=0;const vertices=model.drawables.vertexPositions.map(v=>[...v]);for(const [i,mesh]of plan.meshes.entries())for(let j=0;j<vertices[i].length;j++){const x=mesh.frames[0][j]*(1-value)+mesh.frames[1][j]*value,expected=j%2?(plan.height/2-x)/ppu:(x-plan.width/2)/ppu;assert(Number.isFinite(vertices[i][j]),'Nonfinite runtime vertex');maxError=Math.max(maxError,Math.abs(vertices[i][j]-expected));}assert(maxError<1e-5,'Runtime/source position mismatch');report.samples.push({value,maxError,vertices});}const a=report.samples[1].vertices,z=report.samples[3].vertices;report.changedCoordinateComponents=a.reduce((n,v,i)=>n+v.filter((x,j)=>Math.abs(x-z[i][j])>1e-6).length,0);assert(report.changedCoordinateComponents>0,'No actual parameter motion');fs.writeFileSync(reportFile,JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({status:report.status,changedCoordinateComponents:report.changedCoordinateComponents,report:reportFile}));
}catch(e){console.error(e.message);process.exitCode=1;}finally{model?.release();moc?._release();}
