import {Live2DViewer} from './sdk.js';
import {loadModelSource} from './model-source.js';
import {Conversation} from './conversation.js';
import {BehaviorMap} from './behavior.js';
import {VoicePlayback} from './speech.js';

export async function createLive2DWidget(options={}){
 const host=document.createElement('div'),shadow=host.attachShadow({mode:'open'}),link=document.createElement('link');link.rel='stylesheet';link.href=new URL('./widget.css',import.meta.url);shadow.append(link);
 const ui=document.createElement('div');ui.innerHTML=`<div class="character"><div class="canvas"></div><div class="model-status" role="status">正在加载角色…</div></div><div class="launcher"><button class="toggle" aria-expanded="false">和我聊聊</button><button class="mini minimize" aria-label="收起角色">−</button></div><section class="panel" hidden aria-label="角色对话"><header><strong></strong><select class="model-select" aria-label="更换角色"></select><button class="settings-toggle" aria-label="打开设置">⚙</button><button class="close" aria-label="收起聊天">×</button></header><div class="settings" hidden><label>对话方式<select class="mode"><option value="mock">本地演示</option><option value="direct">自己的供应商 · 会话 BYOK</option><option value="backend">自己的服务器接口</option></select></label><label>完整 HTTPS endpoint<input class="endpoint" type="url" autocomplete="off"></label><label>对话模型 ID<input class="chat-model" autocomplete="off"></label><label>会话 API key（不会保存）<input class="key" type="password" autocomplete="off"></label><label class="runtime-trust"><input class="trust" type="checkbox">我信任这个 endpoint，同意发送消息与会话 key</label><button class="apply">应用对话设置</button><button class="clear">清除会话 key</button><p>供应商需支持本网站 CORS。服务器密钥放你自己的服务器；不会使用公共代理。</p><label><input class="voice-enabled" type="checkbox">朗读回复</label><label>声音<select class="voice-name"><option value="">设备默认声音</option></select></label><div class="voice-row"><label>音量<input class="volume" type="range" min="0" max="1" step=".05"></label><label>语速<input class="rate" type="range" min=".5" max="2" step=".1"></label><label>音调<input class="pitch" type="range" min=".5" max="2" step=".1"></label></div><p class="voice-note"></p><p>麦克风识别取决于浏览器，可能使用浏览器语音服务；仅按下麦克风时请求权限。</p></div><div class="messages" aria-live="polite"></div><form class="chat-form"><textarea class="input" aria-label="消息" placeholder="输入一句话…" maxlength="8000"></textarea><div class="buttons"><button class="send" type="submit">发送</button><button class="stop" type="button" disabled>停止</button><button class="mic" type="button" aria-label="麦克风识别">麦克风</button><button class="clear-chat" type="button">清空</button></div></form><div class="status" role="status">本地演示，无外部调用</div></section>`;shadow.append(ui);
 const $=s=>shadow.querySelector(s);let config=options,disposed=false,loadController,chatController,history=[],sequence=0,collapsed=false;
 const container=options.container||document.body;if(options.container)host.setAttribute('contained','');container.append(host);
 const viewer=new Live2DViewer($('.canvas'),{embedded:true,allowRemote:true,runtimeBase:options.runtimeBase,view:options.appearance});
 const conversation=new Conversation(),behavior=new BehaviorMap(viewer),voice=new VoicePlayback(viewer,text=>status(text));
 const status=text=>{$('.status').textContent=text;};
 const message=(text,role='assistant')=>{const row=document.createElement('div');row.className='message '+role;row.textContent=text;$('.messages').append(row);$('.messages').scrollTop=$('.messages').scrollHeight;return row;};
 function panelWidth(){if(options.container)host.style.setProperty('--panel-width',Math.max(160,Math.min(340,container.clientWidth-2*(Number(config.appearance?.gutter??16)||0)))+'px');}
 const panelObserver=options.container?new ResizeObserver(panelWidth):null;panelObserver?.observe(container);
 function appearance(value={}){const v={width:240,height:360,side:'right',bottom:20,gutter:16,...value};host.setAttribute('side',v.side==='left'?'left':'right');for(const key of ['width','height','bottom','gutter'])host.style.setProperty('--'+key,Math.max(key==='width'?100:key==='height'?160:0,Math.min(key==='width'||key==='height'?700:100,Number(v[key])||0))+'px');panelWidth();viewer.setView({zoom:v.zoom??1,x:v.x??0,y:v.y??0});}
 function open(value=true){$('.panel').hidden=!value;$('.toggle').setAttribute('aria-expanded',String(value));if(value)$('.input').focus();}
 function stop(){chatController?.abort();voice.stop();$('.stop').disabled=true;}
 async function setModel(source){stop();const turn=++sequence;loadController?.abort();viewer.stopFrame();loadController=new AbortController();$('.model-status').hidden=false;$('.model-status').textContent='正在加载角色…';try{if(!source)throw new Error('请先选择模型入口');const model=typeof source==='string'?await loadModelSource(source,{base:config.baseUrl||location.href,signal:loadController.signal}):source;await viewer.load({...model,previewCompatibility:config.compatibility!==false},{signal:loadController.signal});if(turn!==sequence||disposed)return;$('.model-status').hidden=true;const index=(config.models||[]).findIndex(m=>new URL(m.url,config.baseUrl||location.href).href===viewer.model.entryUrl);if(index>=0)$('.model-select').value=index;return model;}catch(e){if(e.name!=='AbortError'&&turn===sequence){$('.model-status').textContent=e.message;status('角色加载失败，可更换模型或重试');}if(e.name!=='AbortError')throw e;}}
 function populateModels(){const entries=config.models||[];$('.model-select').replaceChildren();for(const [index,m] of entries.entries()){const option=document.createElement('option');option.value=index;option.textContent=m.name||'角色 '+(index+1);$('.model-select').append(option);}$('.model-select').hidden=entries.length<2;}
 function voiceSettings(){voice.configure({...config.voice,enabled:$('.voice-enabled').checked,volume:Number($('.volume').value),rate:Number($('.rate').value),pitch:Number($('.pitch').value),voiceName:$('.voice-name').value});}
 function voiceChoices(){const select=$('.voice-name');select.replaceChildren();const d=document.createElement('option');d.value='';d.textContent='设备默认声音';select.append(d);for(const v of voice.voices()){const o=document.createElement('option');o.value=v.name;o.textContent=v.name+' · '+v.lang;select.append(o);}select.value=config.voice?.voiceName||'';}
 function configurePublic(next){stop();config={...config,...next};appearance(config.appearance);$('.panel header strong').textContent=config.title||'Live2D 伙伴';$('.toggle').textContent=config.title?'与 '+config.title+' 聊天':'和我聊聊';$('.mode').value=config.chat?.mode||'mock';$('.endpoint').value=config.chat?.endpoint||'';$('.chat-model').value=config.chat?.model||'';$('.voice-enabled').checked=!!config.voice?.enabled;for(const k of ['volume','rate','pitch'])$('.'+k).value=config.voice?.[k]??1;voiceChoices();voiceSettings();$('.voice-note').textContent=config.voice?.mode==='endpoint'?'使用你配置的音频 TTS，按实际音频波形同步口型。':'系统声音依设备而定；系统朗读口型按发音事件近似。';populateModels();conversation.clear();if(config.chat?.mode==='backend'&&config.chat.endpoint)conversation.configure({...config.chat,trusted:true});status(config.chat?.mode==='backend'?(config.chat.endpoint?'消息发送到你配置的服务器接口':'请在设置中填写可信服务器接口'):config.chat?.mode==='direct'?'请在设置中输入本次会话 key':'本地演示，无外部调用');behavior.configure(config.behavior||{});}
 $('.toggle').onclick=()=>open($('.panel').hidden);$('.close').onclick=()=>open(false);$('.settings-toggle').onclick=()=>{$('.settings').hidden=!$('.settings').hidden;};$('.minimize').onclick=()=>{collapsed=!collapsed;$('.character').hidden=collapsed;$('.minimize').textContent=collapsed?'+':'−';if(collapsed)viewer.pause();else viewer.resume();};
 $('.model-select').onchange=()=>setModel(config.models[Number($('.model-select').value)].url).catch(()=>{});
 $('.apply').onclick=()=>{stop();try{conversation.configure({mode:$('.mode').value,endpoint:$('.endpoint').value,model:$('.chat-model').value,key:$('.key').value,trusted:$('.trust').checked});status(conversation.summary.mode==='mock'?'本地演示已就绪':'已配置 '+new URL(conversation.summary.endpoint).origin+'，仅本次会话');}catch(e){status(e.message);}finally{$('.key').value='';}};
 $('.clear').onclick=()=>{stop();conversation.clear();$('.key').value='';$('.trust').checked=false;status('已清除会话 key，恢复本地演示');};
 for(const k of ['voice-enabled','voice-name','volume','rate','pitch'])$('.'+k).onchange=voiceSettings;
 const voicesChanged=()=>voiceChoices();globalThis.speechSynthesis?.addEventListener('voiceschanged',voicesChanged);
 $('.mic').disabled=!(globalThis.SpeechRecognition||globalThis.webkitSpeechRecognition);$('.mic').onclick=()=>{try{voice.recognize(text=>{$('.input').value=text;});}catch(e){status(e.message);}};
 $('.stop').onclick=stop;$('.clear-chat').onclick=()=>{stop();history=[];$('.messages').replaceChildren();};
 $('.chat-form').onsubmit=async event=>{event.preventDefault();const text=$('.input').value.trim();if(!text||chatController)return;$('.input').value='';message(text,'user');const row=message('正在想…');const controller=new AbortController();chatController=controller;$('.send').disabled=true;$('.stop').disabled=false;status('正在回复…');try{await voice.prepare();if(viewer.ready)behavior.apply('thinking');const messages=[...(config.chat?.systemPrompt?[{role:'system',content:config.chat.systemPrompt}]:[]),...history.slice(-12),{role:'user',content:text}];const reply=await conversation.stream(messages,{signal:controller.signal,onText:value=>{row.textContent=value;$('.messages').scrollTop=$('.messages').scrollHeight;}});if(controller.signal.aborted||disposed)return;history.push({role:'user',content:text},{role:'assistant',content:reply});history=history.slice(-12);if(viewer.ready)behavior.apply('complete');status('回复完成');try{await voice.speak(reply);}catch(e){voice.stop();status('文字回复已完成；语音未完成，请检查浏览器、TTS endpoint 和 CORS');}}catch(e){row.textContent=e.name==='AbortError'?'已停止生成':e.message;row.classList.toggle('error',e.name!=='AbortError');status(e.name==='AbortError'?'已停止':e.message);}finally{if(chatController===controller){chatController=null;$('.send').disabled=false;$('.stop').disabled=true;}}};
 viewer.addEventListener('hit',()=>open(true));viewer.addEventListener('error',e=>{$('.model-status').hidden=false;$('.model-status').textContent=e.detail.message;});
 configurePublic(options);message(options.greeting||'你好！点开设置即可选择自己的对话服务，也可以先体验本地演示。');
 const dispose=()=>{if(disposed)return;disposed=true;++sequence;stop();loadController?.abort();conversation.clear();history=[];panelObserver?.disconnect();viewer.destroy();const cleanup=voice.dispose();globalThis.speechSynthesis?.removeEventListener('voiceschanged',voicesChanged);removeEventListener('pagehide',dispose);host.remove();return cleanup;};addEventListener('pagehide',dispose,{once:true});
 const api={element:host,viewer,open,setModel,setAppearance:appearance,configure:configurePublic,speak:text=>voice.speak(text),stopSpeech:()=>voice.stop(),dispose};
 api.ready=setModel(options.manifest||options.modelUrl||options.models?.[0]?.url).catch(()=>null);return api;
}
