import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {spawnSync} from 'node:child_process';import crypto from 'node:crypto';
import {decodePNG,encodePNG,atlasPNG} from '../scripts/png.mjs';import {planMoc3,planAtlas} from '../studio/moc3-plan.js';
const root=new URL('../',import.meta.url),fixture=JSON.parse(fs.readFileSync(new URL('studio/spec/moc3-synthetic.mesh2d.json',root))),png=Buffer.from(fixture.layers[0].texture.split(',')[1],'base64');
const cli=(...args)=>spawnSync(process.execPath,[new URL('scripts/cli.mjs',root).pathname,...args],{encoding:'utf8'});
test('PNG decode/reencode retains real RGBA pixels and rejects corrupt chunks',()=>{const image=decodePNG(png);assert.deepEqual(decodePNG(encodePNG(image.width,image.height,image.pixels)),image);const bad=Buffer.from(png);bad[20]^=1;assert.throws(()=>decodePNG(bad),/CRC/);});
test('atlas retains original pixels and extrudes edge gutters exactly',()=>{const plan=planMoc3(fixture,'ParamDemo'),atlas=planAtlas(plan),out=decodePNG(atlasPNG(plan,atlas)),image=decodePNG(png),entry=atlas.entries[0];const pixel=(data,w,x,y)=>[...data.subarray((y*w+x)*4,(y*w+x)*4+4)];for(const [x,y]of [[0,0],[255,255],[128,128]])assert.deepEqual(pixel(out.pixels,out.width,entry.x+x,entry.y+y),pixel(image.pixels,image.width,x,y));assert.deepEqual(pixel(out.pixels,out.width,entry.x-2,entry.y),pixel(image.pixels,image.width,0,0));});
test('source package preserves source bytes/keyforms and refuses overwrite',()=>{const out=fs.mkdtempSync(path.join(os.tmpdir(),'live2d-skill-test-'));try{const dest=path.join(out,'new-source'),input=new URL('studio/spec/moc3-synthetic.mesh2d.json',root).pathname;assert.equal(cli('source',input,dest).status,0);assert.deepEqual(fs.readFileSync(path.join(dest,'project.mesh2d.json')),fs.readFileSync(input));assert.equal(cli('source',input,dest).status,1);}finally{fs.rmSync(out,{recursive:true,force:true});}});
test('material manifest creates actual mesh binding; hash/traversal errors reject',()=>{const out=fs.mkdtempSync(path.join(os.tmpdir(),'live2d-skill-material-'));try{const original=new URL('examples/layers.json',root).pathname;assert.equal(cli('materials',original,path.join(out,'good')).status,0);const good=JSON.parse(fs.readFileSync(path.join(out,'good/project.mesh2d.json')));assert.equal(good.layers[0].mesh.positions.length,162);assert.notDeepEqual(good.layers[0].bindings.ParamBreath[0].positions,good.layers[0].bindings.ParamBreath[1].positions);const bad=JSON.parse(fs.readFileSync(original));bad.layers[0].file='../secret.png';fs.writeFileSync(path.join(out,'bad.json'),JSON.stringify(bad));const run=cli('materials',path.join(out,'bad.json'),path.join(out,'bad'));assert.equal(run.status,1);assert.match(run.stderr,/relative PNG/);}finally{fs.rmSync(out,{recursive:true,force:true});}});
test('deterministic runtime export produces genuine identical candidate files',()=>{const out=fs.mkdtempSync(path.join(os.tmpdir(),'live2d-skill-export-'));try{const input=new URL('studio/spec/moc3-synthetic.mesh2d.json',root).pathname;for(const dir of ['a','b'])assert.equal(cli('export',input,path.join(out,dir),'ParamDemo').status,0);const a=fs.readFileSync(path.join(out,'a/candidate-model.zip')),b=fs.readFileSync(path.join(out,'b/candidate-model.zip'));assert.deepEqual(a,b);assert.equal(fs.readFileSync(path.join(out,'a/model.moc3')).toString('ascii',0,4),'MOC3');const report=JSON.parse(fs.readFileSync(path.join(out,'a/VALIDATION.json')));assert.match(report.status,/pending/);assert.equal(report.files['model.moc3'].sha256,crypto.createHash('sha256').update(fs.readFileSync(path.join(out,'a/model.moc3'))).digest('hex'));}finally{fs.rmSync(out,{recursive:true,force:true});}});
test('unsupported same-mesh dynamic combination and source rotation never disappear silently',()=>{const raw=structuredClone(fixture);raw.parameters.push({id:'ParamOther',min:0,max:1,default:0});raw.layers[0].bindings.ParamOther=structuredClone(raw.layers[0].bindings.ParamDemo);assert.throws(()=>planMoc3(raw,'ParamDemo'),/同一网格/);delete raw.layers[0].bindings.ParamOther;raw.layers[0].rotation=20;assert.throws(()=>planMoc3(raw,'ParamDemo'),/未支持字段/);});

test('independent export retains all four motion curves and static null-band geometry',()=>{const out=fs.mkdtempSync(path.join(os.tmpdir(),'live2d-skill-independent-'));try{const input=new URL('studio/spec/moc3-independent.mesh2d.json',root).pathname;assert.equal(cli('export',input,path.join(out,'new'),'ParamBreath').status,0);const dir=path.join(out,'new'),motion=JSON.parse(fs.readFileSync(path.join(dir,'motions/test.motion3.json'))),config=JSON.parse(fs.readFileSync(path.join(dir,'model.model3.json')));assert.deepEqual(motion.Curves.map(c=>c.Id),['ParamBreath','ParamEyeLOpen','ParamEyeROpen','ParamMouthOpenY']);assert.deepEqual(config.StudioRuntime,{profile:'flat-independent-v1',core:6});const plan=planMoc3(JSON.parse(fs.readFileSync(input)));assert.equal(plan.meshes.filter(m=>m.static).length,1);assert.equal(plan.meshes.reduce((n,m)=>n+m.frames.length,0),9);}finally{fs.rmSync(out,{recursive:true,force:true});}});

import {alphaSupport,prepareMaterials} from '../scripts/materials.mjs';
const imageCLI=(...args)=>spawnSync(process.execPath,[new URL('scripts/image-input.mjs',root).pathname,...args],{encoding:'utf8'});
test('alpha support includes separated islands and transparent inputs reject',()=>{const pixels=new Uint8Array(32*32*4);pixels.set([255,1,2,255],(2*32+2)*4);pixels.set([2,1,255,1],(29*32+29)*4);const support=alphaSupport({width:32,height:32,pixels});assert.equal(support.nonzeroPixels,2);assert.deepEqual(support.nonzeroBounds,{left:2,top:2,width:28,height:28});assert.deepEqual(support.support,{left:0,top:0,width:32,height:32});assert.throws(()=>alphaSupport({width:1,height:1,pixels:new Uint8Array(4)}),/Transparent/);});
test('material checks reject duplicated composites, final-hash errors and out-of-canvas layers',()=>{const input=new URL('examples/layers.json',root),m=JSON.parse(fs.readFileSync(input)),base=path.dirname(input.pathname);let bad=structuredClone(m);bad.layers[0].sha256='0'.repeat(64);assert.throws(()=>prepareMaterials(bad,base),/hash mismatch/);bad=structuredClone(m);bad.layers.push({...bad.layers[0],id:'fake-eye',role:'eye.left.open_patch'});assert.throws(()=>prepareMaterials(bad,base),/Duplicated full-canvas composite/);bad=structuredClone(m);bad.layers[0].left=1;assert.throws(()=>prepareMaterials(bad,base),/outside declared canvas/);});
test('image entrypoints create separate candidates and preserve honest single-image/tool limits',()=>{const out=fs.mkdtempSync(path.join(os.tmpdir(),'live2d-image-entry-'));try{const png=new URL('examples/original-geometric.png',root).pathname,license=new URL('LICENSE',root).pathname,layers=new URL('examples/independent-layers/layers.json',root).pathname;assert.equal(imageCLI('layers',layers,path.join(out,'layers')).status,0);const motion=JSON.parse(fs.readFileSync(path.join(out,'layers/runtime/motions/test.motion3.json')));assert.equal(motion.Curves.length,4);assert.ok(fs.existsSync(path.join(out,'layers/editable/editable-project.zip')));assert.equal(imageCLI('single-demo',png,path.join(out,'single'),license).status,0);const raw=JSON.parse(fs.readFileSync(path.join(out,'single/model/editable/project.mesh2d.json')));assert.equal(raw.layers.length,1);assert.equal(raw.layers[0].role,'other');assert.deepEqual(raw.parameters.map(p=>p.id),['ParamBreath']);assert.match(fs.readFileSync(path.join(out,'single/LIMITS.txt'),'utf8'),/No splitting/);assert.equal(imageCLI('tool-request',png,path.join(out,'request'),license).status,0);const request=JSON.parse(fs.readFileSync(path.join(out,'request/tool-request.json')));assert.equal(request.execution.runAutomatically,false);assert.equal(request.execution.privateUploadAuthorized,false);assert.equal(request.review.visualApproved,false);assert.equal(imageCLI('single-demo',png,path.join(out,'single'),license).status,1);}finally{fs.rmSync(out,{recursive:true,force:true});}});
