import {readPSDLayers} from '../v2/psd-layers.js';
import {MESH_FORMAT,gridMesh,validateMeshProject,meshPositions,bindPreset} from '../v2/mesh-project.js';
import {createMeshRenderer} from '../v2/mesh-renderer.js';
import {makeMeshDemo} from './mesh-demo.js';
const $=id=>document.getElementById(id),overlay=$('mesh-canvas'),ctx=overlay.getContext('2d');
let project,renderer,selected=0,parameter='ParamBreath',endpoint=0,playing=false,dirty=false,drag,frame,revision=0,loading,undo=[];
const say=text=>$('status').textContent=text,layer=()=>project?.layers[selected];
const values=()=>Object.fromEntries((project?.parameters||[]).map(p=>[p.id,p.id===parameter?Number($('value').value):p.default]));
function modified(){dirty=true;$('project-name').textContent=(project?.name||'项目')+' · 未保存';}
function history(){const l=layer();if(!l)return;undo.push({id:l.id,bindings:structuredClone(l.bindings)});if(undo.length>60)undo.shift();$('undo').disabled=false;}
function resize(){const r=$('stage').getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2);currentCanvas().width=overlay.width=Math.round(r.width*dpr);currentCanvas().height=overlay.height=Math.round(r.height*dpr);draw();}
function draw(){if(!renderer)return;const v=values();renderer.draw(v);ctx.clearRect(0,0,overlay.width,overlay.height);if(!$('show-mesh').checked||!layer()?.visible)return;const l=layer(),p=meshPositions(l,v),screen=[];for(let i=0;i<p.length;i+=2)screen.push(renderer.toScreen(p[i],p[i+1]));
  ctx.strokeStyle='rgba(53,114,218,.50)';ctx.lineWidth=Math.min(devicePixelRatio||1,2);ctx.beginPath();for(let i=0;i<l.mesh.indices.length;i+=3){const a=screen[l.mesh.indices[i]],b=screen[l.mesh.indices[i+1]],c=screen[l.mesh.indices[i+2]];ctx.moveTo(...a);ctx.lineTo(...b);ctx.lineTo(...c);ctx.lineTo(...a);}ctx.stroke();
  ctx.fillStyle='#3274d6';for(const [x,y]of screen){ctx.beginPath();ctx.arc(x,y,3*Math.min(devicePixelRatio||1,2),0,Math.PI*2);ctx.fill();}}
function sync(){if(!project)return;$('layers').replaceChildren();for(const [i,l]of project.layers.entries()){const row=document.createElement('div'),check=document.createElement('input'),button=document.createElement('button');row.className='layer'+(i===selected?' selected':'');check.type='checkbox';check.checked=l.visible;check.setAttribute('aria-label','显示 '+l.name);check.onchange=()=>{l.visible=check.checked;modified();draw();};button.textContent=l.name;button.onclick=()=>{selected=i;sync();draw();};row.append(check,button);$('layers').append(row);}
  $('selection').textContent=layer().name+' · '+layer().mesh.positions.length/2+' 顶点';$('opacity').value=layer().opacity;$('parameter').replaceChildren();for(const p of project.parameters){const o=document.createElement('option');o.value=p.id;o.textContent=p.name+' · '+p.id;$('parameter').append(o);}if(!project.parameters.some(p=>p.id===parameter))parameter=project.parameters[0]?.id||'';$('parameter').value=parameter;
  $('value-label').value=Number($('value').value).toFixed(2);$('key-zero').classList.toggle('active',endpoint===0);$('key-one').classList.toggle('active',endpoint===1);$('binding-info').textContent=layer().bindings[parameter]?'已绑定两个端点；暂停后可拖点精修。':'当前层尚未绑定此参数；可创建预设或直接拖点。';$('undo').disabled=!undo.length;}
function stop(){playing=false;$('play').textContent='循环播放当前参数';cancelAnimationFrame(frame);}
async function install(raw){const token=++revision;loading?.abort();loading=new AbortController();const checked=validateMeshProject(raw);const nextCanvas=document.createElement('canvas');nextCanvas.width=currentCanvas().width;nextCanvas.height=currentCanvas().height;const next=await createMeshRenderer(nextCanvas,checked,{signal:loading.signal});if(token!==revision){next.dispose();return;}stop();renderer?.dispose();currentCanvas().replaceWith(nextCanvas);nextCanvas.id='art-canvas';project=checked;renderer=next;selected=0;parameter=checked.parameters[0]?.id||'';endpoint=0;$('value').value=0;undo=[];dirty=false;$('project-name').textContent=project.name;sync();resize();say(`已打开 ${project.layers.length} 层。像素与网格留在本标签页内存中。`);}
// Canvas is replaced for each import so a failed decode cannot destroy the working project.
function currentCanvas(){return $('art-canvas');}
async function fromPSD(file){const parsed=readPSDLayers(await file.arrayBuffer()),layers=[];for(const l of parsed.layers){const c=document.createElement('canvas');c.width=l.width;c.height=l.height;c.getContext('2d').putImageData(new ImageData(l.rgba,l.width,l.height),0,0);const {rgba,left,top,...rest}=l;layers.push({...rest,texture:c.toDataURL('image/png'),mesh:gridMesh(left,top,l.width,l.height),bindings:{}});}return {format:MESH_FORMAT,version:1,name:file.name.replace(/\.psd$/i,''),width:parsed.width,height:parsed.height,layers,parameters:[{id:'ParamBreath',name:'呼吸',min:0,max:1,default:0}]};}
$('art-file').onchange=async()=>{const file=$('art-file').files[0];if(!file)return;try{if(file.size>64*1024*1024)throw new Error('素材超过 64 MiB');say('正在本地解码分层像素…');let p;if(/\.psd$/i.test(file.name))p=await fromPSD(file);else{const data=new Uint8Array(await file.arrayBuffer());if(data.length<24||data.slice(0,8).join(',')!=='137,80,78,71,13,10,26,10')throw new Error('请选择 PNG');const view=new DataView(data.buffer),w=view.getUint32(16),h=view.getUint32(20);if(!w||!h||w>4096||h>4096)throw new Error('PNG 尺寸超过 4096');const image=await createImageBitmap(file),c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d').drawImage(image,0,0);image.close();p={format:MESH_FORMAT,version:1,name:file.name.replace(/\.png$/i,''),width:w,height:h,layers:[{id:'layer-0',name:'图层 1',width:w,height:h,visible:true,opacity:1,texture:c.toDataURL(),mesh:gridMesh(0,0,w,h),bindings:{}}],parameters:[{id:'ParamBreath',name:'呼吸',min:0,max:1,default:0}]};}await install(p);}catch(e){say(e.message);}finally{$('art-file').value='';}};
$('project-file').onchange=async()=>{const file=$('project-file').files[0];if(!file)return;try{if(file.size>64*1024*1024)throw new Error('项目超过 64 MiB');await install(JSON.parse(await file.text()));}catch(e){say(e.message);}finally{$('project-file').value='';}};
function download(){if(!project)return say('先导入或打开项目');const checked=validateMeshProject(project),blob=new Blob([JSON.stringify(checked)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=project.name.replace(/[\\/:*?"<>|]/g,'_')+'.mesh2d.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);dirty=false;$('project-name').textContent=project.name;say('项目已下载。重新打开此文件会恢复纹理、网格与参数端点。');}
$('save').onclick=download;
$('play-page').onclick=()=>{if(!project)return say('先导入或打开项目');say('先保存项目；在网页播放页选择这个 .mesh2d.json 文件。');window.open('./mesh-player.html','_blank','noopener');};
$('demo').onclick=async()=>{try{await install(makeMeshDemo());}catch(e){say(e.message);}};
$('parameter').onchange=()=>{stop();parameter=$('parameter').value;endpoint=0;$('value').value=0;sync();draw();};
$('add-parameter').onclick=()=>{if(!project)return say('先打开项目');if(project.parameters.length>=16)return say('第一版最多 16 个参数');const name=$('parameter-name').value.trim();if(!name)return say('请填写参数名字');let id=/眨眼|眼/.test(name)?'ParamEyeLOpen':/嘴|口/.test(name)?'ParamMouthOpenY':/呼吸/.test(name)?'ParamBreath':'ParamCustom';let suffix=1,base=id;while(project.parameters.some(p=>p.id===id))id=base+suffix++;project.parameters.push({id,name,min:0,max:1,default:0});parameter=id;$('parameter-name').value='';modified();sync();draw();};
function key(value){stop();endpoint=value;$('value').value=value;sync();draw();}
$('key-zero').onclick=()=>key(0);$('key-one').onclick=()=>key(1);
$('value').oninput=()=>{stop();$('value-label').value=Number($('value').value).toFixed(2);draw();};
$('show-mesh').onchange=draw;
$('apply-preset').onclick=()=>{if(!layer()||!parameter)return say('先选择图层和参数');history();bindPreset(layer(),parameter,$('preset').value,Number($('strength').value));modified();key(1);say('已写入真实网格端点。拖动参数滑块检查形状。');};
$('reset-binding').onclick=()=>{if(!layer())return;history();delete layer().bindings[parameter];modified();sync();draw();};
$('opacity').oninput=()=>{if(!layer())return;layer().opacity=Number($('opacity').value);modified();draw();};
$('undo').onclick=()=>{const old=undo.pop();if(!old)return;const l=project.layers.find(l=>l.id===old.id);if(l)l.bindings=old.bindings;modified();sync();draw();};
for(const [id,direction]of [['layer-down',-1],['layer-up',1]])$(id).onclick=()=>{if(!project)return;const next=selected+direction;if(next<0||next>=project.layers.length)return;[project.layers[selected],project.layers[next]]=[project.layers[next],project.layers[selected]];selected=next;sync();draw();modified();};
$('reverse').onclick=()=>{if(!project)return;project.layers.reverse();selected=project.layers.length-1-selected;sync();draw();modified();};
$('play').onclick=()=>{if(!project||!parameter)return say('先选择参数');if(playing){stop();return;}playing=true;$('play').textContent='暂停播放';const start=performance.now();function tick(time){if(!playing)return;$('value').value=(1-Math.cos((time-start)/1000*2))/2;$('value-label').value=Number($('value').value).toFixed(2);draw();frame=requestAnimationFrame(tick);}frame=requestAnimationFrame(tick);};
overlay.onpointerdown=e=>{if(!layer()||playing||!parameter)return;const r=overlay.getBoundingClientRect(),scale=overlay.width/r.width,p=meshPositions(layer(),values());let best=-1,distance=14*scale;for(let i=0;i<p.length;i+=2){const [x,y]=renderer.toScreen(p[i],p[i+1]),d=Math.hypot(x-(e.clientX-r.left)*scale,y-(e.clientY-r.top)*scale);if(d<distance){best=i;distance=d;}}if(best<0)return;history();if(!layer().bindings[parameter])layer().bindings[parameter]=[{value:0,positions:layer().mesh.positions.slice()},{value:1,positions:layer().mesh.positions.slice()}];$('value').value=endpoint;drag=best;overlay.setPointerCapture(e.pointerId);};
overlay.onpointermove=e=>{if(drag===undefined)return;const r=overlay.getBoundingClientRect(),s=overlay.width/r.width,[x,y]=renderer.toDocument((e.clientX-r.left)*s,(e.clientY-r.top)*s),positions=layer().bindings[parameter][endpoint].positions;positions[drag]=x;positions[drag+1]=y;modified();draw();};
overlay.onpointerup=e=>{drag=undefined;try{overlay.releasePointerCapture(e.pointerId);}catch{}sync();};overlay.onpointercancel=()=>drag=undefined;
new ResizeObserver(resize).observe($('stage'));addEventListener('pagehide',()=>{stop();loading?.abort();renderer?.dispose();});
// Read-only diagnostics for reproducible local verification; no model or binary export API.
window.meshEditorDiagnostics=()=>project?{projectName:project.name,layerCount:project.layers.length,parameter,selected,endpoint,value:Number($('value').value),dirty,positions:meshPositions(layer(),values()),project:validateMeshProject(project)}:null;
