import {readPSDLayers} from '../v2/psd-layers.js';
import {MESH_FORMAT,gridMesh,validateMeshProject,meshPositions,bindPreset} from '../v2/mesh-project.js?ui=3';
import {createMeshRenderer} from '../v2/mesh-renderer.js?ui=3';
import {makeMeshDemo} from './mesh-demo.js?ui=3';
import {EditHistory,editorState,restoreEditorState,layerState,transformGeometry,parameterMotion,basicBreath,boundsFor,selectedInBox} from './mesh-editing.js?ui=3';
import {launchPreview} from './mesh-handoff.js?ui=3';
import {MATERIAL_ROLES,defaultActionParameters,inferMaterialRole,applyMaterialManifest,mainAlphaBounds} from '../v2/material-contract.js?ui=3';
import {ACTIONS,ensureActionParameters,inferProjectRoles,actionStatus,bindBasicAction,bindAllBasics,actionSignature} from './mesh-actions.js?ui=3';
import {guardMoc3Structure,planMoc3} from './moc3-plan.js?ui=4';
import {launchMoc3Export} from './moc3-handoff.js?ui=4';
let moc3SourceWarning='',moc3Close;
const $=id=>document.getElementById(id),overlay=$('mesh-canvas'),ctx=overlay.getContext('2d');
let project,renderer,selected=0,parameter='',endpoint=0,mode='layer',target='base',playing=false,dirty=false,gesture,frame,revision=0,loading;
let selection=new Set(),history=new EditHistory(),baseline=new Map(),savedSignature='',opacityBefore,previewClose;
const say=text=>$('status').textContent=text,layer=()=>project?.layers[selected],currentCanvas=()=>$('art-canvas');
const values=()=>Object.fromEntries((project?.parameters||[]).map(p=>[p.id,p.id===parameter?Number($('value').value):p.default]));
const allPoints=()=>Array.from({length:(layer()?.mesh.positions.length||0)/2},(_,i)=>i);
const indices=()=>mode==='layer'?allPoints():[...selection];
function changed(){dirty=JSON.stringify(editorState(project))!==savedSignature;$('project-name').textContent=project.name+(dirty?' · 未保存':'');}
function commit(before,label){history.push(before,editorState(project),label);changed();sync();draw();}
function edit(label,action){if(!project)return;cancelGesture();stop();const before=editorState(project);try{action();commit(before,label);}catch(error){restoreEditorState(project,before);changed();sync();draw();throw error;}}
function stop(){playing=false;$('play').textContent='循环预览当前参数';cancelAnimationFrame(frame);}
function resize(){const r=$('stage').getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2);currentCanvas().width=overlay.width=Math.round(r.width*dpr);currentCanvas().height=overlay.height=Math.round(r.height*dpr);draw();}
const handleDirections=[[-1,-1],[0,-1],[1,-1],[1,0],[1,1],[0,1],[-1,1],[-1,0]];
function controlBox(){if(!renderer||!layer()?.visible)return null;const p=meshPositions(layer(),values()),ids=indices(),b=boundsFor(p,ids);if(!b||ids.length<2||b.right-b.left<1||b.bottom-b.top<1)return null;const a=renderer.toScreen(b.left,b.top),z=renderer.toScreen(b.right,b.bottom),pad=mode==='mesh'?10*Math.min(devicePixelRatio||1,2):0;return {document:b,left:a[0]-pad,top:a[1]-pad,right:z[0]+pad,bottom:z[1]+pad};}
function handles(box){return handleDirections.map(([x,y])=>({x:x<0?box.left:x>0?box.right:(box.left+box.right)/2,y:y<0?box.top:y>0?box.bottom:(box.top+box.bottom)/2,direction:[x,y]}));}
function draw(){if(!renderer)return;const v=values();renderer.draw(v);ctx.clearRect(0,0,overlay.width,overlay.height);if(!layer()?.visible)return;
  const l=layer(),p=meshPositions(l,v),screen=[],dpr=Math.min(devicePixelRatio||1,2);for(let i=0;i<p.length;i+=2)screen.push(renderer.toScreen(p[i],p[i+1]));
  if($('show-mesh').checked){ctx.strokeStyle='rgba(53,114,218,.35)';ctx.lineWidth=dpr;ctx.beginPath();for(let i=0;i<l.mesh.indices.length;i+=3){const [a,b,c]=l.mesh.indices.slice(i,i+3).map(n=>screen[n]);ctx.moveTo(...a);ctx.lineTo(...b);ctx.lineTo(...c);ctx.lineTo(...a);}ctx.stroke();}
  if(mode==='mesh')screen.forEach(([x,y],i)=>{ctx.fillStyle=selection.has(i)?'#d27a27':'#3274d6';ctx.strokeStyle='white';ctx.lineWidth=dpr;ctx.beginPath();ctx.arc(x,y,(selection.has(i)?4.5:3)*dpr,0,Math.PI*2);ctx.fill();ctx.stroke();});
  const box=controlBox();if(box){ctx.strokeStyle=mode==='layer'?'#315e44':'#d27a27';ctx.lineWidth=1.5*dpr;ctx.setLineDash(mode==='mesh'?[4*dpr,3*dpr]:[]);ctx.strokeRect(box.left,box.top,box.right-box.left,box.bottom-box.top);ctx.setLineDash([]);for(const h of handles(box)){ctx.fillStyle='white';ctx.fillRect(h.x-4*dpr,h.y-4*dpr,8*dpr,8*dpr);ctx.strokeRect(h.x-4*dpr,h.y-4*dpr,8*dpr,8*dpr);}}
  if(gesture?.kind==='marquee'){const b=gesture.screen;ctx.fillStyle='rgba(50,116,214,.10)';ctx.strokeStyle='#3274d6';ctx.lineWidth=dpr;ctx.setLineDash([4*dpr,3*dpr]);ctx.fillRect(b.left,b.top,b.right-b.left,b.bottom-b.top);ctx.strokeRect(b.left,b.top,b.right-b.left,b.bottom-b.top);ctx.setLineDash([]);}
}
function sync(){
  $('undo').disabled=!history.canUndo;$('redo').disabled=!history.canRedo;$('tool-layer').classList.toggle('active',mode==='layer');$('tool-mesh').classList.toggle('active',mode==='mesh');
  $('tool-layer').setAttribute('aria-pressed',String(mode==='layer'));$('tool-mesh').setAttribute('aria-pressed',String(mode==='mesh'));$('edit-target').value=target;$('point-controls').hidden=mode!=='mesh';$('reset-edit').textContent=target==='base'?'重置此层（含端点）':'重置当前端点';overlay.style.cursor=mode==='layer'?'move':'crosshair';
  const scope=target==='base'?'基础姿态：此层的所有参数端点同步变换':`参数 ${parameter||'未选择'} 的端点 ${endpoint}：只修改这个形状`;
  $('edit-scope').textContent=scope;$('tool-hint').textContent=(mode==='layer'?'拖动边框内区域移动整层；拖动白色柄缩放。':'空白处拖框选点，Shift 点选增减；拖动已选点共同移动，白色柄缩放选区。图层边界包含透明区域。')+' '+(target==='base'?'基础姿态修改会保留原有关键帧形变。':'滑块中间值仅预览；先选择端点 0 或 1 再编辑。');
  if(!project)return;$('layers').replaceChildren();for(const [i,l]of project.layers.entries()){const row=document.createElement('div'),check=document.createElement('input'),button=document.createElement('button');row.className='layer'+(i===selected?' selected':'');check.type='checkbox';check.checked=l.visible;check.setAttribute('aria-label','显示 '+l.name);check.onchange=()=>edit('图层显示',()=>{l.visible=check.checked;});button.textContent=l.name;button.onclick=()=>{cancelGesture();selected=i;selection.clear();sync();draw();};row.append(check,button);$('layers').append(row);}
  $('selection').textContent=layer().name+' · '+layer().mesh.positions.length/2+' 顶点'+(mode==='mesh'?' · 已选 '+selection.size:'');$('opacity').value=layer().opacity;
  $('parameter').replaceChildren();for(const p of project.parameters){const o=document.createElement('option');o.value=p.id;o.textContent=p.name+' · '+p.id;$('parameter').append(o);}if(!project.parameters.some(p=>p.id===parameter))parameter=project.parameters[0]?.id||'';$('parameter').value=parameter;
  $('value-label').value=Number($('value').value).toFixed(2);for(const [id,n]of [['key-zero',0],['key-one',1]]){const active=target==='endpoint'&&endpoint===n;$(id).classList.toggle('active',active);$(id).setAttribute('aria-pressed',String(active));}
  const keys=layer().bindings[parameter],different=keys?.[0].positions.some((v,i)=>Math.abs(v-keys[1].positions[i])>1e-7);$('binding-info').textContent=different?'此层两个端点形状不同，可循环预览。':keys?'两个端点形状相同，播放不会产生变化。':'此层未绑定当前参数；可用预设创建两个不同形状。';
  const p=project.parameters.find(p=>p.id===parameter),eye=/eye.*open/i.test(parameter),kind=eye?'blink':/mouth/i.test(parameter)?'mouth':/breath/i.test(parameter)?'breath':'sway';$('preset').value=kind;updateStrengthNote();
  $('parameter-info').textContent=eye?(p?.semantics==='eye-open-01'?'眼睛：0 闭、1 开，默认张开。当前预设仍是压扁近似。':'旧项目眼睛：0 开、1 压扁闭合，保留原有播放方向。后续标准导出需显式反向映射。'):/mouth/i.test(parameter)?'张嘴：0 为基础嘴形、1 为拉伸嘴形；不会补画口内像素。':'0 为基础形状、1 为变形形状；滑块中间值用于插值预览。';
  $('apply-preset').textContent=`绑定到 ${p?.name||'当前参数'} · ${layer().name}`;$('material-role').value=layer().role||'other';$('material-role-info').textContent=layer().roleSource==='manifest'?'来自对应 PSD 哈希的素材规范；视觉质量仍需检查。':layer().roleSource==='manual'?'手动指定的材料角色；不代表像素质量已合格。':'按图层名称建议的材料角色；请检查实际像素。';
  renderActions();
  $('motion-guide').hidden=project.parameters.some(p=>parameterMotion(project,p.id).changedCoordinates>0);$('edit-scope').textContent=target==='base'?scope:`参数 ${parameter||'未选择'} 的端点 ${endpoint}：只修改这个形状`;
}
function renderActions(){if(!project)return;$('action-catalog').replaceChildren();for(const action of ACTIONS){const stat=actionStatus(project,action.id),card=document.createElement('div'),title=document.createElement('strong'),state=document.createElement('span'),note=document.createElement('small');card.className='action-card';card.dataset.action=action.id;title.textContent=action.name;state.className='action-state '+stat.state;state.textContent=stat.label;note.textContent=stat.note;card.append(title,state,note);
  if(action.id!=='wave'){const button=document.createElement('button');button.textContent='创建基础绑定';button.onclick=()=>{try{let result;edit('创建'+action.name,()=>{result=bindBasicAction(project,action.id,Number($('strength').value));});say(`${action.name}：新建 ${result.created} 层，保留 ${result.preserved} 层已有端点。${result.status.note}`);}catch(error){say(error.message);}};card.append(button);}
  if(action.id==='breath'&&stat.changedCoordinates){const review=document.createElement('button');review.textContent='已检查呼吸 0/1 画面';review.disabled=stat.state==='usable';review.onclick=()=>edit('确认基础呼吸画面',()=>{project.actionReviews??={};project.actionReviews.breath=actionSignature(project,'breath');});card.append(review);}$('action-catalog').append(card);}}
function updateStrengthNote(){const blink=$('preset').value==='blink';$('strength').disabled=blink;$('strength-note').textContent=blink?'压扁比例固定为 6%；此预设不使用幅度滑块。':'幅度用于呼吸、轻摆和嘴层拉伸。';}
$('preset').onchange=updateStrengthNote;
for(const role of MATERIAL_ROLES){const option=document.createElement('option');option.value=role;option.textContent=role==='other'?'未指定 / 其他':role;$('material-role').append(option);}
$('material-role').onchange=()=>{if(!layer())return;edit('指定材料角色',()=>{layer().role=$('material-role').value;layer().roleSource='manual';project.actionReviews={};});};
$('bind-basics').onclick=()=>{if(!project)return say('先导入素材');try{let results;edit('创建基础动作绑定',()=>{results=bindAllBasics(project,Number($('strength').value));});say(results.map(r=>`${r.action}：新建 ${r.created}，保留 ${r.preserved}，${r.status.label}`).join('；')+'。请检查画面；眼嘴仅近似。');}catch(error){say(error.message);}};
$('add-wave').onclick=()=>{if(!project)return say('先导入素材');try{edit('添加可选招手参数',()=>ensureActionParameters(project,{wave:true}));say('已添加招手参数槽位；关节招手尚未实现，缺素材或绑定时不会显示可用。');}catch(error){say(error.message);}};
$('materials-file').onchange=async()=>{const file=$('materials-file').files[0];if(!file)return;try{if(!project)throw new Error('先导入对应 PSD');if(file.size>2*1024*1024)throw new Error('图层规范超过 2 MiB');const manifest=JSON.parse(await file.text());let count;edit('导入素材图层规范',()=>{count=applyMaterialManifest(project,manifest);});say(`原 PSD 哈希匹配，已对应 ${count} 层角色；还需实际视觉检查，再创建基础绑定。`);}catch(error){say(error.message);}finally{$('materials-file').value='';}};
function cancelGesture(){if(!gesture)return;if(gesture.before)restoreEditorState(project,gesture.before);try{overlay.releasePointerCapture(gesture.pointerId);}catch{}gesture=null;changed();sync();draw();}
async function install(raw){let sourceWarning='';try{guardMoc3Structure(raw);}catch(error){sourceWarning=error.message;}cancelGesture();const token=++revision;loading?.abort();loading=new AbortController();const checked=inferProjectRoles(validateMeshProject(raw));ensureActionParameters(checked,{allowFull:true});const nextCanvas=document.createElement('canvas');nextCanvas.width=currentCanvas().width;nextCanvas.height=currentCanvas().height;const next=await createMeshRenderer(nextCanvas,checked,{signal:loading.signal});if(token!==revision){next.dispose();return;}stop();renderer?.dispose();currentCanvas().replaceWith(nextCanvas);nextCanvas.id='art-canvas';project=checked;moc3SourceWarning=sourceWarning;renderer=next;selected=0;parameter=checked.parameters[0]?.id||'';endpoint=0;mode='layer';target='base';selection.clear();$('value').value=0;$('show-mesh').checked=false;opacityBefore=null;history=new EditHistory();baseline=new Map(project.layers.map(l=>[l.id,layerState(l)]));savedSignature=JSON.stringify(editorState(project));dirty=false;$('project-name').textContent=project.name;sync();resize();say(`已打开 ${project.layers.length} 层。基础动作目录会显示缺层、未绑定或近似；参数名字不代表动作已完成。`);}
async function fromPSD(file){const buffer=await file.arrayBuffer(),parsed=readPSDLayers(buffer),layers=[],sha256=[...new Uint8Array(await crypto.subtle.digest('SHA-256',buffer))].map(x=>x.toString(16).padStart(2,'0')).join('');for(const l of parsed.layers){const c=document.createElement('canvas');c.width=l.width;c.height=l.height;c.getContext('2d').putImageData(new ImageData(l.rgba,l.width,l.height),0,0);const {rgba,left,top,...rest}=l;layers.push({...rest,texture:c.toDataURL('image/png'),mesh:gridMesh(left,top,l.width,l.height),bindings:{},role:inferMaterialRole(l.name),roleSource:'inferred',...(inferMaterialRole(l.name)==='mouth.closed_patch'?{contentBounds:mainAlphaBounds(rgba,l.width,l.height,left,top)}:{})});}const p={format:MESH_FORMAT,version:1,name:file.name.replace(/\.psd$/i,''),width:parsed.width,height:parsed.height,layers,parameters:defaultActionParameters(),sourceAsset:{sha256,kind:'psd'}};if($('auto-bind-import').checked)bindAllBasics(p);return p;}
$('art-file').onchange=async()=>{const file=$('art-file').files[0];if(!file)return;try{if(file.size>64*1024*1024)throw new Error('素材超过 64 MiB');say('正在本地解码分层像素…');let p;if(/\.psd$/i.test(file.name))p=await fromPSD(file);else{const data=new Uint8Array(await file.arrayBuffer());if(data.length<24||data.slice(0,8).join(',')!=='137,80,78,71,13,10,26,10')throw new Error('请选择 PNG');const view=new DataView(data.buffer),w=view.getUint32(16),h=view.getUint32(20);if(!w||!h||w>4096||h>4096)throw new Error('PNG 尺寸超过 4096');const image=await createImageBitmap(file),c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d').drawImage(image,0,0);image.close();p={format:MESH_FORMAT,version:1,name:file.name.replace(/\.png$/i,''),width:w,height:h,layers:[{id:'layer-0',name:'图层 1',width:w,height:h,visible:true,opacity:1,texture:c.toDataURL(),mesh:gridMesh(0,0,w,h),bindings:{}}],parameters:defaultActionParameters()};}await install(p);}catch(e){say(e.message);}finally{$('art-file').value='';}};
$('project-file').onchange=async()=>{const file=$('project-file').files[0];if(!file)return;try{if(file.size>64*1024*1024)throw new Error('项目超过 64 MiB');await install(JSON.parse(await file.text()));}catch(e){say(e.message);}finally{$('project-file').value='';}};
function download(){if(!project)return say('先导入或打开项目');try{const checked=validateMeshProject(project),blob=new Blob([JSON.stringify(checked)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=project.name.replace(/[\\/:*?"<>|]/g,'_')+'.mesh2d.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);savedSignature=JSON.stringify(editorState(project));changed();say('已下载自定义网页网格项目，可重开继续编辑；这不是 Cubism MOC3。');}catch(e){say(e.message);}}
$('moc3-export').onclick=()=>{if(!project)return say('先打开项目');try{if(moc3SourceWarning)throw new Error(moc3SourceWarning);planMoc3(project,parameter);stop();moc3Close?.();moc3Close=launchMoc3Export(validateMeshProject(project),say);}catch(error){say(error.message);}};
$('save').onclick=download;$('play-page').onclick=()=>{if(!project)return say('先导入或打开项目');try{previewClose?.();previewClose=launchPreview(validateMeshProject(project),say);}catch(e){say(e.message);}};
$('demo').onclick=async()=>{try{await install(makeMeshDemo());say('已主动打开原创几何演示。重新导入文件可回到自己的项目。');}catch(e){say(e.message);}};
for(const name of ['layer','mesh'])$('tool-'+name).onclick=()=>{cancelGesture();mode=name;if(name==='mesh')$('show-mesh').checked=true;sync();draw();};
$('edit-target').onchange=()=>{cancelGesture();target=$('edit-target').value;stop();if(target==='endpoint')$('value').value=endpoint;sync();draw();};
$('select-all').onclick=()=>{selection=new Set(allPoints());sync();draw();};$('clear-selection').onclick=()=>{selection.clear();sync();draw();};
$('parameter').onchange=()=>{cancelGesture();stop();parameter=$('parameter').value;endpoint=0;$('value').value=0;sync();draw();};
$('add-parameter').onclick=()=>{if(!project)return say('先打开项目');if(project.parameters.length>=16)return say('第一版最多 16 个参数');const name=$('parameter-name').value.trim();if(!name)return say('请填写参数名字');edit('添加参数',()=>{let id=/右眼/.test(name)?'ParamEyeROpen':/眨眼|眼/.test(name)?'ParamEyeLOpen':/嘴|口/.test(name)?'ParamMouthOpenY':/呼吸/.test(name)?'ParamBreath':/招手|挥手/.test(name)?'ParamWave':'ParamCustom',suffix=1,base=id;while(project.parameters.some(p=>p.id===id))id=base+suffix++;project.parameters.push({id,name,min:0,max:1,default:/eye.*open/i.test(id)?1:0,...(/eye.*open/i.test(id)?{semantics:'eye-open-01'}:{})});parameter=id;endpoint=0;$('value').value=0;$('parameter-name').value='';});};
function key(value){cancelGesture();stop();endpoint=value;target='endpoint';$('value').value=value;sync();draw();}
$('key-zero').onclick=()=>key(0);$('key-one').onclick=()=>key(1);$('value').oninput=()=>{cancelGesture();stop();$('value-label').value=Number($('value').value).toFixed(2);draw();};$('show-mesh').onchange=draw;
$('apply-preset').onclick=()=>{if(!layer()||!parameter)return say('先选择图层和参数');edit('绑定预设',()=>bindPreset(layer(),parameter,$('preset').value,Number($('strength').value),{semantics:project.parameters.find(p=>p.id===parameter)?.semantics}));key(1);say('已创建当前层的两个网格端点；切换 0/1 或循环预览检查效果。');};
$('reset-binding').onclick=()=>{if(!layer()||!parameter)return;edit('清除参数绑定',()=>delete layer().bindings[parameter]);say('已清除当前层的这个参数绑定，其他参数保留；可以撤销。');};
$('reset-edit').onclick=()=>{if(!layer())return;edit(target==='base'?'重置图层':'重置端点',()=>{if(target==='base'){const s=baseline.get(layer().id);Object.assign(layer(),structuredClone(s));}else if(layer().bindings[parameter])layer().bindings[parameter][endpoint].positions=layer().mesh.positions.slice();});say(target==='base'?'已恢复此层打开项目时的形状和全部端点；可以撤销。':'已将当前端点恢复为基础网格，另一个端点保留；可以撤销。');};
$('opacity').oninput=()=>{if(!layer())return;opacityBefore??=editorState(project);layer().opacity=Number($('opacity').value);changed();draw();};$('opacity').onchange=()=>{if(opacityBefore){commit(opacityBefore,'透明度');opacityBefore=null;}};
function navigateHistory(direction){if(!project)return;cancelGesture();stop();const id=layer().id,label=history[direction](project);if(!label)return;selected=Math.max(0,project.layers.findIndex(l=>l.id===id));changed();sync();draw();say((direction==='undo'?'已撤销：':'已重做：')+label);}
$('undo').onclick=()=>navigateHistory('undo');$('redo').onclick=()=>navigateHistory('redo');
for(const [id,direction]of [['layer-down',-1],['layer-up',1]])$(id).onclick=()=>{if(!project)return;const next=selected+direction;if(next<0||next>=project.layers.length)return;edit('图层顺序',()=>{[project.layers[selected],project.layers[next]]=[project.layers[next],project.layers[selected]];selected=next;});};
$('reverse').onclick=()=>{if(!project)return;edit('反转图层顺序',()=>{project.layers.reverse();selected=project.layers.length-1-selected;});};
function loop(){if(!project||!parameter)return say('先选择参数');if(!parameterMotion(project,parameter).changedCoordinates)return say('当前参数没有可变化的端点；请先绑定预设或使用一键基础呼吸。');playing=true;$('play').textContent='暂停预览';const start=performance.now();function tick(time){if(!playing)return;$('value').value=(1-Math.cos((time-start)/1000*2))/2;$('value-label').value=Number($('value').value).toFixed(2);draw();frame=requestAnimationFrame(tick);}frame=requestAnimationFrame(tick);}
$('play').onclick=()=>playing?stop():loop();$('quick-breath').onclick=()=>{if(!project)return;try{let result;edit('基础呼吸',()=>{result=basicBreath(project,{selected});selected=result.index;parameter=result.id;endpoint=1;target='endpoint';selection.clear();});loop();say((result.created?'已给 '+layer().name+' 创建基础呼吸。':'已保留现有呼吸绑定。')+'当前是实时预览；暂停后可编辑端点。');}catch(error){say(error.message);}};
function pointer(e){const r=overlay.getBoundingClientRect(),scale=overlay.width/r.width,screen=[(e.clientX-r.left)*scale,(e.clientY-r.top)*scale];return {screen,document:renderer.toDocument(...screen)};}
function editable(){if(target==='endpoint'&&(!parameter||Math.abs(Number($('value').value)-endpoint)>.001)){say('中间值只用于预览。先点击“编辑端点 0”或“编辑端点 1”，再拖动。');return false;}return true;}
function startGesture(e,kind,point,extra={}){gesture={kind,pointerId:e.pointerId,from:point.document,fromScreen:point.screen,before:kind==='marquee'?null:editorState(project),source:kind==='marquee'?null:layerState(layer()),reference:meshPositions(layer(),values()),ids:indices(),...extra};overlay.setPointerCapture(e.pointerId);overlay.focus({preventScroll:true});draw();}
function handleAt(screen,box){if(!box)return null;const radius=9*Math.min(devicePixelRatio||1,2);return handles(box).find(h=>Math.hypot(screen[0]-h.x,screen[1]-h.y)<radius);}
function pointAt(screen){const p=meshPositions(layer(),values());let best=-1,distance=12*Math.min(devicePixelRatio||1,2);for(let i=0;i<p.length;i+=2){const q=renderer.toScreen(p[i],p[i+1]),d=Math.hypot(q[0]-screen[0],q[1]-screen[1]);if(d<distance){best=i/2;distance=d;}}return best;}
function startScale(e,p,h,box){if(!editable())return;const b=box.document,[x,y]=h.direction,pivot=[x<0?b.right:x>0?b.left:(b.left+b.right)/2,y<0?b.bottom:y>0?b.top:(b.top+b.bottom)/2];startGesture(e,'scale',p,{bounds:b,direction:h.direction,pivot});}
overlay.onpointerdown=e=>{if(!renderer||!layer()?.visible||e.button!==0)return;stop();const p=pointer(e),box=controlBox(),handle=!e.shiftKey&&handleAt(p.screen,box);if(handle){startScale(e,p,handle,box);return;}
  if(mode==='layer'){if(!box||p.screen[0]<box.left||p.screen[0]>box.right||p.screen[1]<box.top||p.screen[1]>box.bottom)return;if(editable())startGesture(e,'move',p);return;}
  const hit=pointAt(p.screen);if(hit>=0){if(e.shiftKey){if(selection.has(hit)){selection.delete(hit);sync();draw();return;}selection.add(hit);}else if(!selection.has(hit))selection=new Set([hit]);sync();draw();if(editable())startGesture(e,'move',p);}
  else startGesture(e,'marquee',p,{previousSelection:e.shiftKey?new Set(selection):new Set(),screen:{left:p.screen[0],top:p.screen[1],right:p.screen[0],bottom:p.screen[1]}});
};
overlay.onpointermove=e=>{if(!gesture){if(renderer&&layer()?.visible){const h=handleAt(pointer(e).screen,controlBox());overlay.style.cursor=h?(h.direction[0]&&h.direction[1]?(h.direction[0]===h.direction[1]?'nwse-resize':'nesw-resize'):h.direction[0]?'ew-resize':'ns-resize'):mode==='layer'?'move':'crosshair';}return;}
  const p=pointer(e),g=gesture;if(g.kind==='marquee'){g.screen={left:Math.min(g.fromScreen[0],p.screen[0]),top:Math.min(g.fromScreen[1],p.screen[1]),right:Math.max(g.fromScreen[0],p.screen[0]),bottom:Math.max(g.fromScreen[1],p.screen[1])};g.box={left:Math.min(g.from[0],p.document[0]),top:Math.min(g.from[1],p.document[1]),right:Math.max(g.from[0],p.document[0]),bottom:Math.max(g.from[1],p.document[1])};draw();return;}
  const dx=p.document[0]-g.from[0],dy=p.document[1]-g.from[1];let sx=1,sy=1;if(g.kind==='scale'){const [x,y]=g.direction,b=g.bounds;if(x)sx=1+dx/(x*(b.right-b.left));if(y)sy=1+dy/(y*(b.bottom-b.top));if($('lock-ratio').checked){const s=x&&y?(Math.abs(sx-1)>Math.abs(sy-1)?sx:sy):x?sx:sy;sx=sy=s;}sx=Math.max(.05,Math.min(20,sx));sy=Math.max(.05,Math.min(20,sy));}
  try{transformGeometry(layer(),g.source,{indices:g.ids,target,parameter,endpoint,dx:g.kind==='move'?dx:0,dy:g.kind==='move'?dy:0,sx,sy,pivot:g.pivot||[0,0],reference:g.reference});changed();draw();}catch(error){say(error.message);}
};
overlay.onpointerup=e=>{if(!gesture)return;const g=gesture;if(g.kind==='marquee'){selection=new Set([...g.previousSelection,...selectedInBox(layer(),values(),g.box||{left:g.from[0],top:g.from[1],right:g.from[0],bottom:g.from[1]})]);}gesture=null;try{overlay.releasePointerCapture(e.pointerId);}catch{}if(g.before)commit(g.before,g.kind==='scale'?'缩放'+(mode==='layer'?'整层':'选中顶点'):'移动'+(mode==='layer'?'整层':'选中顶点'));else{sync();draw();}};
overlay.onpointercancel=cancelGesture;
addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&!e.target.matches('input:not([type=range]),textarea')){if(e.key.toLowerCase()==='z'){e.preventDefault();navigateHistory(e.shiftKey?'redo':'undo');}else if(e.key.toLowerCase()==='y'){e.preventDefault();navigateHistory('redo');}}if(e.key==='Escape'&&gesture){e.preventDefault();cancelGesture();}if(e.target===overlay&&e.key.startsWith('Arrow')&&project&&indices().length&&editable()){e.preventDefault();const n=e.shiftKey?10:1;edit('键盘移动',()=>transformGeometry(layer(),layerState(layer()),{indices:indices(),target,parameter,endpoint,dx:e.key==='ArrowRight'?n:e.key==='ArrowLeft'?-n:0,dy:e.key==='ArrowDown'?n:e.key==='ArrowUp'?-n:0,reference:meshPositions(layer(),values())}));}});
new ResizeObserver(resize).observe($('stage'));addEventListener('pagehide',()=>{stop();previewClose?.();moc3Close?.();loading?.abort();renderer?.dispose();});sync();
window.meshEditorDiagnostics=()=>project?{projectName:project.name,layerCount:project.layers.length,parameter,selected,endpoint,value:Number($('value').value),dirty,mode,target,selection:[...selection],positions:meshPositions(layer(),values()),motion:project.parameters.map(p=>parameterMotion(project,p.id)),project:validateMeshProject(project)}:null;
