import {createLive2DWidget} from '../v2/widget.js?ui=3';
import {validateMeshProject,meshModel} from '../v2/mesh-project.js?ui=3';
import {makeMeshDemo} from './mesh-demo.js?ui=3';
import {parameterMotion,basicBreath} from './mesh-editing.js?ui=3';
import {actionStatus,inferProjectRoles} from './mesh-actions.js?ui=3';
import {receivePreview} from './mesh-handoff.js?ui=3';
const $=id=>document.getElementById(id);let widget,url,turn=0,paused=false,project,source='',controls=new Map();
const say=text=>$('status').textContent=text;
function auto(){widget?.viewer.command('mesh-playback',{breath:$('auto-breath').checked&&!$('auto-breath').disabled,blink:$('auto-blink').checked&&!$('auto-blink').disabled});}
function updateState(state){for(const [id,c]of controls){const value=Number(state.values?.[id]);if(!Number.isFinite(value))continue;if(document.activeElement!==c.range)c.range.value=value;c.output.value=(document.activeElement===c.range?Number(c.range.value):value).toFixed(2);}
  $('motion-status').textContent=state.paused?'角色已暂停。':$('auto-breath').checked?'呼吸正在循环，数值与画面同步更新。':$('auto-blink').checked?'眨眼正在自动播放。':'当前由手动参数控制。';}
async function open(raw,{from='本地文件'}={}){const token=++turn,checked=inferProjectRoles(validateMeshProject(raw)),nextURL=URL.createObjectURL(new Blob([JSON.stringify(checked)],{type:'application/json'}));widget?.dispose();if(url)URL.revokeObjectURL(url);url=nextURL;project=checked;source=from;
  const next=await createLive2DWidget({container:$('preview'),manifest:meshModel(project,url,{localImport:true}),title:project.name,appearance:{width:330,height:500,side:'right',bottom:24,gutter:20},chat:{mode:'unconfigured'},voice:{enabled:false}});if(token!==turn){next.dispose();return;}widget=next;
  next.viewer.addEventListener('mesh-state',e=>{if(token===turn)updateState(e.detail);});await next.ready;if(token!==turn)return;if(!next.viewer.ready)throw new Error(next.viewer.lastError||'网格项目加载失败');
  paused=false;$('pause').textContent='暂停角色';$('project-name').textContent=project.name+' · '+from;$('parameters').replaceChildren();controls=new Map();
  const motion=project.parameters.map(p=>parameterMotion(project,p.id)),breath=motion.filter(m=>/breath/i.test(m.id)),blink=motion.filter(m=>/eye.*open/i.test(m.id));
  for(const [label,checkbox,stats]of [['breath-control','auto-breath',breath],['blink-control','auto-blink',blink]]){$(label).hidden=!stats.length;$(checkbox).disabled=!stats.some(m=>m.changedCoordinates);$(checkbox).checked=!$(checkbox).disabled;}
  for(const p of project.parameters){const stat=motion.find(m=>m.id===p.id),label=document.createElement('label'),range=document.createElement('input'),output=document.createElement('output'),note=document.createElement('small');label.textContent=p.name+' · '+p.id;range.type='range';range.min=0;range.max=1;range.step=.01;range.value=p.default;range.dataset.parameter=p.id;range.setAttribute('aria-label',p.name);range.disabled=!stat.changedCoordinates;output.value=p.default.toFixed(2);const action=/breath/i.test(p.id)?'breath':/eye.*open/i.test(p.id)?'blink':/mouth.*open/i.test(p.id)?'mouth':null;note.textContent=stat.changedCoordinates?'已绑定 '+stat.boundLayers+' 个可见图层'+(action?' · '+actionStatus(project,action).label:''):'未绑定不同端点，当前只静态显示';if(/wave/i.test(p.id))note.textContent+=' · 关节招手尚未实现';if(/eye.*open/i.test(p.id))note.textContent+=p.semantics==='eye-open-01'?' · 0 闭 / 1 开':' · 旧项目 0 开 / 1 闭';
    range.oninput=()=>{output.value=Number(range.value).toFixed(2);if(/breath/i.test(p.id))$('auto-breath').checked=false;if(/eye.*open/i.test(p.id))$('auto-blink').checked=false;auto();widget.viewer.setMeshParameter(p.id,Number(range.value));};label.append(output,range,note);$('parameters').append(label);controls.set(p.id,{range,output});}
  const moving=motion.some(m=>m.changedCoordinates);$('motion-guide').hidden=moving;$('static-note').textContent='当前项目的两个参数端点尚无有效差异，角色只会静态显示。可添加基础呼吸，再保存带绑定的项目。';auto();if(next.viewer.meshState)updateState(next.viewer.meshState);
  say(moving?'已加载你的项目。自动参数值会实时变化；效果很小时请检查幅度、所选图层和遮挡。':'已加载你的真实角色，未替换为演示。当前没有有效形变绑定；可点击“添加基础呼吸”。');}
$('auto-breath').onchange=auto;$('auto-blink').onchange=auto;
$('project-file').onchange=async()=>{const file=$('project-file').files[0];if(!file)return;try{if(file.size>64*1024*1024)throw new Error('项目超过 64 MiB');await open(JSON.parse(await file.text()));}catch(e){say('项目加载失败：'+e.message+'。没有切换到演示。');}finally{$('project-file').value='';}};
$('demo').onclick=()=>open(makeMeshDemo(),{from:'主动选择的原创几何演示'}).catch(e=>say('演示加载失败：'+e.message));
$('pause').onclick=()=>{if(!widget)return;paused=!paused;paused?widget.viewer.pause():widget.viewer.resume();$('pause').textContent=paused?'继续播放':'暂停角色';};
$('add-breath').onclick=async()=>{if(!project)return;try{const next=structuredClone(project),result=basicBreath(next);await open(next,{from:'当前项目 · 已添加基础呼吸'});say('已给 '+next.layers[result.index].name+' 添加基础呼吸。点击“保存当前项目”下载带绑定版本；原文件保留。');}catch(e){say('无法添加呼吸：'+e.message);}};
$('save-project').onclick=()=>{if(!project)return say('先打开自己的项目');try{const blob=new Blob([JSON.stringify(validateMeshProject(project))],{type:'application/json'}),downloadURL=URL.createObjectURL(blob),a=document.createElement('a');a.href=downloadURL;a.download=project.name.replace(/[\\/:*?"<>|]/g,'_')+'.mesh2d.json';a.click();setTimeout(()=>URL.revokeObjectURL(downloadURL),1000);say('当前纹理、网格和参数端点已下载；保存格式是自定义网页 mesh2d，不是 MOC3。');}catch(e){say(e.message);}};
const session=new URLSearchParams(location.hash.slice(1)).get('session');if(session){say('正在接收编辑器的当前项目，包含未保存的修改…');receivePreview(session).then(async received=>{try{await open(received.project,{from:'编辑器当前项目（含未保存编辑）'});received.complete();history.replaceState(null,'',location.pathname+location.search);}catch(error){received.complete(error);say('当前项目加载失败：'+error.message+'。请回编辑器重试，或打开保存的文件；没有切换到演示。');}}).catch(error=>say(error.message+' 没有切换到演示。'));}
addEventListener('pagehide',()=>{widget?.dispose();if(url)URL.revokeObjectURL(url);});window.meshPlayerDiagnostics=()=>({ready:widget?.viewer.ready,error:widget?.viewer.lastError,source,manifest:widget?.viewer.model,values:widget?.viewer.meshState?.values,motion:project?.parameters.map(p=>parameterMotion(project,p.id)),capabilities:widget?.viewer.listCapabilities()});
