import {planMoc3,planAtlas,writerInput,modelReferences,testMotion} from './moc3-plan.js?ui=4';
import {createMeshRenderer} from '../v2/mesh-renderer.js?ui=3';
let createCubism53Viewer;
import {zipFiles,downloadBlob} from '../v2/export.js';
import {readZip} from '../v2/importer.js';
import {loadMoc3Core} from './moc3-core.js?ui=4';
import {receiveMoc3Project} from './moc3-handoff.js?ui=4';
const $=id=>document.getElementById(id),encoder=new TextEncoder();
let raw,plan,atlas,files,source,viewer,model,core,manual=true,value=0,report={},urls=[];
const sha=async bytes=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes)),v=>v.toString(16).padStart(2,'0')).join('');
const json=value=>JSON.stringify(value,null,2)+'\n';
const snapshot=()=>({value:core.getParameterValueByIndex(0),vertices:Array.from({length:core.getDrawableCount()},(_,i)=>[...core.getDrawableVertexPositions(i)])});
const updateReport=()=>{$('report').textContent=json(report);};
const failure=error=>{report.error={stage:report.stage,message:error.message};$('status').textContent='验证失败：'+error.message;$('download').disabled=true;updateReport();console.error(error);};
const blobURL=bytes=>{const url=URL.createObjectURL(new Blob([bytes]));urls.push(url);return url;};
function clearModel(){model?.release();model=null;core=null;viewer=null;for(const url of urls)URL.revokeObjectURL(url);urls=[];}
function controls(enabled){for(const id of ['zero','half','one','motion','compare','review','audit'])$(id).disabled=!enabled;}
function drawSource(next){const defaults=Object.fromEntries(raw.parameters.map(p=>[p.id,p.default]));source.draw({...defaults,[plan.mapping.sourceParameter]:plan.mapping.legacyEyeReversed?1-next:next},{zoom:1/.9,x:0,y:0});}
function setValue(next){manual=true;value=next;core.setParameterValueByIndex(0,next);core.saveParameters();core.update();model.draw();drawSource(next);report.manualSamples??=[];report.manualSamples.push(snapshot());updateReport();}
window.moc3IntegrationDiagnostics=()=>({...report,current:core?snapshot():null});
function assert(test,message){if(!test)throw new Error(message);}

async function textureAtlas(){const canvas=document.createElement('canvas');canvas.width=canvas.height=atlas.size;const ctx=canvas.getContext('2d');
  for(const entry of atlas.entries){const mesh=plan.meshes.find(m=>m.id===entry.id),image=new Image();await new Promise((resolve,reject)=>{image.onload=resolve;image.onerror=()=>reject(new Error('PNG 无法解码'));image.src=mesh.texture;});
    assert(image.width===entry.width&&image.height===entry.height,'实际 PNG 尺寸与计划不符');const {x,y,width:w,height:h}=entry;ctx.drawImage(image,x,y);
    ctx.drawImage(image,0,0,1,h,x-2,y,2,h);ctx.drawImage(image,w-1,0,1,h,x+w,y,2,h);ctx.drawImage(image,0,0,w,1,x,y-2,w,2);ctx.drawImage(image,0,h-1,w,1,x,y+h,w,2);
    for(const [sx,sy,dx,dy]of [[0,0,x-2,y-2],[w-1,0,x+w,y-2],[0,h-1,x-2,y+h],[w-1,h-1,x+w,y+h]])ctx.drawImage(image,sx,sy,1,1,dx,dy,2,2);
  }return new Uint8Array(await(await new Promise(resolve=>canvas.toBlob(resolve,'image/png'))).arrayBuffer());}

function validateCore(binary){const runtime=Live2DCubismCore,consistent=runtime.Moc.prototype.hasMocConsistency(binary);assert(consistent===1,'官方 Core 一致性拒绝：'+consistent);let moc,instance;
  const result={consistency:consistent,samples:[],meshes:[],changedCoordinateComponents:0};
  try{moc=runtime.Moc.fromArrayBuffer(binary);assert(moc,'Moc 加载失败');instance=runtime.Model.fromMoc(moc);assert(instance,'Model 加载失败');
    assert(instance.parameters.count===1&&instance.parameters.ids[0]===plan.parameter.id,'运行时参数不符');assert(instance.parameters.minimumValues[0]===0&&instance.parameters.maximumValues[0]===1&&Math.abs(instance.parameters.defaultValues[0]-plan.parameter.default)<1e-6,'参数范围／默认值不符');assert(instance.drawables.count===plan.meshes.length,'图层数量不符');
  instance.update();const ppu=Math.max(plan.width,plan.height);for(let i=0;i<plan.meshes.length;i++){const mesh=plan.meshes[i],entry=atlas.entries.find(e=>e.id===mesh.id);
      assert(instance.drawables.vertexCounts[i]===mesh.frames[0].length/2,'顶点数量不符');assert(instance.drawables.indices[i].length===mesh.indices.length,'三角形数量不符');
      assert(instance.drawables.textureIndices[i]===0&&Math.abs(instance.drawables.opacities[i]-mesh.opacity)<1e-5,'贴图／透明度不符');
      const expectedUV=mesh.uvs.map((uv,j)=>j%2?1-(entry.y+uv*mesh.height)/atlas.size:(entry.x+uv*mesh.width)/atlas.size);const uvError=Math.max(...expectedUV.map((uv,j)=>Math.abs(uv-instance.drawables.vertexUvs[i][j])));assert(uvError<1e-5,'纹理 UV 不符');
      const expectedIndices=mesh.indices.flatMap((_,j)=>j%3===0?[mesh.indices[j+2],mesh.indices[j+1],mesh.indices[j]]:[]);assert(expectedIndices.every((index,j)=>index===instance.drawables.indices[i][j]),'三角形索引不符：'+JSON.stringify([...instance.drawables.indices[i]]));
      assert(instance.renderOrders[i]===plan.meshes.length-1-i,'实际渲染层序不符');result.meshes.push({id:mesh.id,runtimeId:instance.drawables.ids[i],vertexCount:instance.drawables.vertexCounts[i],triangleCount:mesh.indices.length/3,uvError,drawOrder:instance.drawables.drawOrders[i],renderOrder:instance.renderOrders[i]});
    }
    for(const next of [0,.5,1,0,plan.parameter.default]){instance.parameters.values[0]=next;instance.update();let maxError=0;const vertices=[];for(let i=0;i<plan.meshes.length;i++){const mesh=plan.meshes[i],actual=[...instance.drawables.vertexPositions[i]];vertices.push(actual);for(let j=0;j<actual.length;j++){const source=mesh.frames[0][j]*(1-next)+mesh.frames[1][j]*next,expected=j%2?(plan.height/2-source)/ppu:(source-plan.width/2)/ppu;maxError=Math.max(maxError,Math.abs(actual[j]-expected));}}assert(maxError<1e-5,'运行时顶点与源关键形不符：'+maxError);result.samples.push({value:next,maxError,vertices});}
    result.changedCoordinateComponents=result.samples[0].vertices.reduce((n,v,i)=>n+v.filter((x,j)=>Math.abs(x-result.samples[2].vertices[i][j])>1e-6).length,0);assert(result.changedCoordinateComponents>0,'模型没有实际运动');return result;
  }finally{instance?.release();moc?._release();}}

async function loadGenerated(){clearModel();report.stage='framework-render-load';const config=JSON.parse(new TextDecoder().decode(files.get('model.model3.json'))),mocBytes=files.get(config.FileReferences.Moc);
  const width=Math.min(512,plan.width),height=Math.round(width*plan.height/plan.width);viewer=await createCubism53Viewer({container:$('target'),width,height,config,mocBytes,textureURLs:config.FileReferences.Textures.map(name=>blobURL(files.get(name))),readJSON:async name=>JSON.parse(new TextDecoder().decode(files.get(name))),resolveResource:name=>name});
  model=viewer.getModel();core=model.getModel();model.getModelMatrix().setHeight(2*height/width);
  const original=model.update.bind(model);model.update=()=>{original();if(manual){core.setParameterValueByIndex(0,value);core.update();}else{drawSource(core.getParameterValueByIndex(0));if((report.frames||0)%5===0&&report.motionSamples.length<240)report.motionSamples.push(snapshot());}report.frames=(report.frames||0)+1;};
  viewer.start();setValue(plan.parameter.default);report.frameworkLoaded=true;report.stage='rendered-awaiting-review';controls(true);$('status').textContent='真实模型已加载。比较 0 / 0.5 / 1，再播放动作并检查两侧画面。';updateReport();}

async function acceptProject(text,name){controls(false);$('download').disabled=true;$('review').checked=false;clearModel();source?.dispose();assert(encoder.encode(text).length<=64*1024*1024,'项目超过预算');raw=JSON.parse(text);report={sourceFile:name,sourceSHA256:await sha(encoder.encode(text)),stage:'input-loaded',motionSamples:[]};$('parameter').replaceChildren(...raw.parameters.map(parameter=>{const option=document.createElement('option');option.value=parameter.id;option.textContent=parameter.id;return option;}));$('generate').disabled=false;$('status').textContent='本地项目已读取，等待生成。';updateReport();}
$('project').onchange=async()=>{try{const file=$('project').files[0];if(file)await acceptProject(await file.text(),file.name);}catch(error){failure(error);}};
$('sample').onclick=async()=>{try{const response=await fetch(new URL('./spec/moc3-synthetic.mesh2d.json',import.meta.url),{credentials:'omit',redirect:'error'});if(!response.ok)throw new Error('合成样例无法读取');await acceptProject(await response.text(),'原创合成样例');}catch(error){failure(error);}};
const session=new URLSearchParams(location.hash.slice(1)).get('session');if(session)receiveMoc3Project(session).then(async delivery=>{try{await acceptProject(JSON.stringify(delivery.project),'编辑器当前项目（含未保存编辑）');delivery.complete();}catch(error){delivery.complete(error);failure(error);}}).catch(failure);
$('generate').onclick=async()=>{try{$('generate').disabled=true;$('project').disabled=true;$('parameter').disabled=true;controls(false);$('download').disabled=true;$('review').checked=false;clearModel();source?.dispose();report={sourceFile:report.sourceFile,sourceSHA256:report.sourceSHA256,stage:'input-boundary',motionSamples:[]};plan=planMoc3(raw,$('parameter').value);atlas=planAtlas(plan);report.support={parameter:plan.parameter,mapping:plan.mapping,visibleLayers:plan.meshes.length,atlasSize:atlas.size,warnings:plan.warnings};
  const freshCanvas=document.createElement('canvas');freshCanvas.id='source';$('source').replaceWith(freshCanvas);freshCanvas.width=Math.min(512,plan.width);freshCanvas.height=Math.round(freshCanvas.width*plan.height/plan.width);source=await createMeshRenderer(freshCanvas,raw);drawSource(plan.parameter.default);
  report.stage='atlas';const png=await textureAtlas();report.stage='worker-writer';const input=writerInput(plan,atlas),worker=new Worker(new URL('./moc3-worker.js',import.meta.url),{type:'module'});const binary=await new Promise((resolve,reject)=>{const timeout=setTimeout(()=>{worker.terminate();reject(new Error('导出器超时'));},15000);worker.onmessage=event=>{clearTimeout(timeout);worker.terminate();event.data.error?reject(new Error(event.data.error.message)):resolve(event.data.binary);};worker.onerror=error=>{clearTimeout(timeout);worker.terminate();reject(new Error(error.message));};worker.postMessage(input);});
  assert(binary instanceof ArrayBuffer&&binary.byteLength>=1984&&binary.byteLength<=8*1024*1024,'导出二进制超出预算');report.mocBytes=binary.byteLength;report.mocSHA256=await sha(binary);report.stage='official-core';await loadMoc3Core();({createCubism53Viewer}=await import('../v2/cubism53-viewer.js?moc3=4'));report.core=validateCore(binary);
  const bytes=value=>encoder.encode(json(value));files=new Map([['model.moc3',new Uint8Array(binary)],['model.model3.json',bytes(modelReferences())],['textures/texture_00.png',png],['motions/test.motion3.json',bytes(testMotion(plan))]]);
  const license=await fetch('../vendor/experimental-moc3/LICENSE.MIT').then(r=>r.text());files.set('WRITER-LICENSE.txt',encoder.encode(license));report.fileHashes=Object.fromEntries(await Promise.all([...files].map(async([name,data])=>[name,await sha(data)])));await loadGenerated();
  }catch(error){failure(error);}finally{$('generate').disabled=false;$('project').disabled=false;$('parameter').disabled=false;}};
for(const [id,next]of [['zero',0],['half',.5],['one',1]])$(id).onclick=()=>setValue(next);
$('motion').onclick=()=>{manual=false;report.motionSamples=[];report.stage='motion-playing';model.startMotion('Test',0,3);$('status').textContent='正在播放导出 model3 引用的真实测试动作。';};
$('compare').onclick=()=>{const sourceCanvas=$('source'),targetCanvas=$('target').querySelector('canvas'),read=canvas=>{const copy=document.createElement('canvas');copy.width=canvas.width;copy.height=canvas.height;const ctx=copy.getContext('2d');ctx.drawImage(canvas,0,0);return ctx.getImageData(0,0,copy.width,copy.height).data;};model.draw();drawSource(core.getParameterValueByIndex(0));const a=read(sourceCanvas),b=read(targetCanvas);let changed=0,total=0,alphaMismatch=0,visiblePixels=0,hash=2166136261;for(let i=0;i<a.length;i+=4){let pixel=false;for(let j=0;j<4;j++){hash=Math.imul(hash^b[i+j],16777619);const delta=Math.abs(a[i+j]-b[i+j]);total+=delta;if(delta>3)pixel=true;}if(pixel)changed++;if(b[i+3]>16)visiblePixels++;if(Math.abs(a[i+3]-b[i+3])>3)alphaMismatch++;}report.pixelComparisons??=[];report.pixelComparisons.push({value:core.getParameterValueByIndex(0),width:sourceCanvas.width,height:sourceCanvas.height,pixels:sourceCanvas.width*sourceCanvas.height,changedPixelsAbove3:changed,alphaMismatch,visiblePixels,renderedPixelHash:(hash>>>0).toString(16),meanAbsoluteChannelError:total/a.length});updateReport();};
function acceptance(){const comparisons=report.pixelComparisons||[],samples=[0,.5,1].map(value=>comparisons.findLast(sample=>Math.abs(sample.value-value)<1e-5));const motionDistinct=new Set(report.motionSamples.map(sample=>JSON.stringify(sample.vertices))).size;
  const pixelsWithinTolerance=samples.every(sample=>sample&&sample.visiblePixels>0&&sample.meanAbsoluteChannelError<=1&&sample.changedPixelsAbove3/sample.pixels<=.03&&sample.alphaMismatch/sample.pixels<=.01),renderedEndpointMotion=!!(samples[0]&&samples[2]&&samples[0].renderedPixelHash!==samples[2].renderedPixelHash);
  return {samplesPresent:samples.every(Boolean),pixelsWithinTolerance,renderedEndpointMotion,motionDistinct,accepted:pixelsWithinTolerance&&renderedEndpointMotion&&motionDistinct>1&&!report.error&&report.frameworkLoaded};}
$('review').onchange=()=>{report.acceptance=acceptance();$('download').disabled=!$('review').checked||!report.acceptance.accepted;if($('review').checked&&!report.acceptance.accepted)$('status').textContent='下载尚未通过：需核对 0 / 0.5 / 1 画面且播放真实动作，画面对比不能超过容差。';updateReport();};
$('download').onclick=async()=>{try{report.acceptance=acceptance();assert(report.acceptance.accepted&&$('review').checked,'模型包验收门槛尚未满足');report.visualApproved=$('review').checked;report.stage='verified-package-download';files.set('VALIDATION.json',encoder.encode(json(report)));files.set('README.txt',encoder.encode('Experimental flat ArtMesh MOC3. Exactly one animated parameter; no rotation, hierarchy, masks, physics or complete blink/mouth/wave rig. Generated locally. Official Core is not included. Keep WRITER-LICENSE.txt.\n'));downloadBlob(zipFiles(files),'single-parameter-moc3.zip');updateReport();}catch(error){failure(error);}};
$('package').onchange=async()=>{try{report.stage='zip-reopen';const file=$('package').files[0];const imported=await readZip(await file.arrayBuffer());const reopened=new Map(imported.files);for(const name of ['model.moc3','model.model3.json','textures/texture_00.png','motions/test.motion3.json'])assert(await sha(reopened.get(name))===report.fileHashes[name],'重新打开文件哈希不符：'+name);for(const [name,data]of reopened)files.set(name,data);report.reopenedCore=validateCore(files.get('model.moc3').buffer.slice(files.get('model.moc3').byteOffset,files.get('model.moc3').byteOffset+files.get('model.moc3').byteLength));report.zipReopenHashesMatched=true;await loadGenerated();report.stage='zip-reopened-rendered';$('status').textContent='ZIP 模型文件哈希一致，官方 Core 和渲染器重新加载成功。';updateReport();}catch(error){failure(error);}};
$('audit').onclick=()=>downloadBlob(new Blob([json({...report,current:snapshot()})],{type:'application/json'}),'validation-report.json');
addEventListener('pagehide',()=>{clearModel();source?.dispose();},{once:true});
