import {planMoc3,planAtlas,writerInput,modelReferences,testMotion,parameterSamples,sourceValues} from './moc3-plan.js?ui=5';
import {validateMoc3Core} from './moc3-validation.js?ui=5';
import {createMeshRenderer} from '../v2/mesh-renderer.js?ui=3';
let createCubism53Viewer;
import {zipFiles,downloadBlob} from '../v2/export.js';
import {readZip} from '../v2/importer.js';
import {loadMoc3Core} from './moc3-core.js?ui=4';
import {receiveMoc3Project} from './moc3-handoff.js?ui=5';
const $=id=>document.getElementById(id),encoder=new TextEncoder();
let raw,plan,atlas,files,source,viewer,model,core,manual=true,value=0,values={},activeIndex=0,report={},urls=[];
const sha=async bytes=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes)),v=>v.toString(16).padStart(2,'0')).join('');
const json=value=>JSON.stringify(value,null,2)+'\n';
const snapshot=()=>({value:core.getParameterValueByIndex(activeIndex),values:Object.fromEntries(plan.parameters.map((p,i)=>[p.id,core.getParameterValueByIndex(i)])),vertices:Array.from({length:core.getDrawableCount()},(_,i)=>[...core.getDrawableVertexPositions(i)])});
const updateReport=()=>{$('report').textContent=json(report);};
const failure=error=>{report.error={stage:report.stage,message:error.message};$('status').textContent='验证失败：'+error.message;$('download').disabled=true;updateReport();console.error(error);};
const blobURL=bytes=>{const url=URL.createObjectURL(new Blob([bytes]));urls.push(url);return url;};
function clearModel(){model?.release();model=null;core=null;viewer=null;for(const url of urls)URL.revokeObjectURL(url);urls=[];}
function controls(enabled){for(const id of ['zero','half','one','motion','compare','combinations','source-download','review','audit'])$(id).disabled=!enabled;}
const defaults=()=>Object.fromEntries(plan.parameters.map(p=>[p.id,p.default]));
function drawSource(){const frozen=Object.fromEntries(raw.parameters.map(p=>[p.id,p.default]));source.draw({...frozen,...sourceValues(plan,values)},{zoom:1/.9,x:0,y:0});}
function setValues(next){manual=true;values={...next};value=values[plan.parameters[activeIndex].id];for(const [i,p]of plan.parameters.entries())core.setParameterValueByIndex(i,values[p.id]);core.saveParameters();core.update();model.draw();drawSource();report.manualSamples??=[];report.manualSamples.push(snapshot());updateReport();}
function setValue(next){setValues({...defaults(),[plan.parameters[activeIndex].id]:next});}
window.moc3IntegrationDiagnostics=()=>({...report,current:core?snapshot():null});
function assert(test,message){if(!test)throw new Error(message);}

async function textureAtlas(){const canvas=document.createElement('canvas');canvas.width=canvas.height=atlas.size;const ctx=canvas.getContext('2d');
  for(const entry of atlas.entries){const mesh=plan.meshes.find(m=>m.id===entry.id),image=new Image();await new Promise((resolve,reject)=>{image.onload=resolve;image.onerror=()=>reject(new Error('PNG 无法解码'));image.src=mesh.texture;});
    assert(image.width===entry.width&&image.height===entry.height,'实际 PNG 尺寸与计划不符');const {x,y,width:w,height:h}=entry;ctx.drawImage(image,x,y);
    ctx.drawImage(image,0,0,1,h,x-2,y,2,h);ctx.drawImage(image,w-1,0,1,h,x+w,y,2,h);ctx.drawImage(image,0,0,w,1,x,y-2,w,2);ctx.drawImage(image,0,h-1,w,1,x,y+h,w,2);
    for(const [sx,sy,dx,dy]of [[0,0,x-2,y-2],[w-1,0,x+w,y-2],[0,h-1,x-2,y+h],[w-1,h-1,x+w,y+h]])ctx.drawImage(image,sx,sy,1,1,dx,dy,2,2);
  }return new Uint8Array(await(await new Promise(resolve=>canvas.toBlob(resolve,'image/png'))).arrayBuffer());}

function validateCore(binary){return validateMoc3Core(Live2DCubismCore,binary,plan,atlas);}

async function loadGenerated(){clearModel();report.stage='framework-render-load';const config=JSON.parse(new TextDecoder().decode(files.get('model.model3.json'))),mocBytes=files.get(config.FileReferences.Moc);
  const width=Math.min(512,plan.width),height=Math.round(width*plan.height/plan.width);viewer=await createCubism53Viewer({container:$('target'),width,height,config,mocBytes,textureURLs:config.FileReferences.Textures.map(name=>blobURL(files.get(name))),readJSON:async name=>JSON.parse(new TextDecoder().decode(files.get(name))),resolveResource:name=>name});
  model=viewer.getModel();core=model.getModel();model.getModelMatrix().setHeight(2*height/width);
  const original=model.update.bind(model);model.update=()=>{original();if(manual){for(const [i,p]of plan.parameters.entries())core.setParameterValueByIndex(i,values[p.id]);core.update();}else{values=Object.fromEntries(plan.parameters.map((p,i)=>[p.id,core.getParameterValueByIndex(i)]));drawSource();if((report.frames||0)%5===0&&report.motionSamples.length<240)report.motionSamples.push(snapshot());}report.frames=(report.frames||0)+1;};
  viewer.start();setValues(defaults());report.frameworkLoaded=true;report.stage='rendered-awaiting-review';controls(true);$('status').textContent='真实模型已加载。核对全部独立组合，再播放动作并检查两侧画面；单参数也可比较 0 / 0.5 / 1。';updateReport();}

async function acceptProject(text,name){controls(false);$('download').disabled=true;$('review').checked=false;clearModel();plan=null;atlas=null;files=null;values={};source?.dispose();assert(encoder.encode(text).length<=64*1024*1024,'项目超过预算');raw=JSON.parse(text);report={sourceFile:name,sourceSHA256:await sha(encoder.encode(text)),stage:'input-loaded',motionSamples:[]};$('parameter').replaceChildren(...raw.parameters.map(parameter=>{const option=document.createElement('option');option.value=parameter.id;option.textContent=parameter.id;return option;}));$('generate').disabled=false;$('status').textContent='本地项目已读取，等待生成。';updateReport();}
$('source-download').onclick=()=>downloadBlob(new Blob([json(raw)],{type:'application/json'}),raw.name.replace(/[\\/:*?"<>|]/g,'_')+'.mesh2d.json');
$('multi-sample').onclick=async()=>{try{const response=await fetch(new URL('./spec/moc3-independent.mesh2d.json',import.meta.url),{credentials:'omit',redirect:'error'});if(!response.ok)throw new Error('四参数样例无法读取');await acceptProject(await response.text(),'原创四参数几何样例');}catch(error){failure(error);}};
$('project').onchange=async()=>{try{const file=$('project').files[0];if(file)await acceptProject(await file.text(),file.name);}catch(error){failure(error);}};
$('sample').onclick=async()=>{try{const response=await fetch(new URL('./spec/moc3-synthetic.mesh2d.json',import.meta.url),{credentials:'omit',redirect:'error'});if(!response.ok)throw new Error('合成样例无法读取');await acceptProject(await response.text(),'原创合成样例');}catch(error){failure(error);}};
const session=new URLSearchParams(location.hash.slice(1)).get('session');if(session)receiveMoc3Project(session).then(async delivery=>{try{await acceptProject(JSON.stringify(delivery.project),'编辑器当前项目（含未保存编辑）');delivery.complete();}catch(error){delivery.complete(error);failure(error);}}).catch(failure);
$('generate').onclick=async()=>{try{$('generate').disabled=true;$('project').disabled=true;$('parameter').disabled=true;$('sample').disabled=$('multi-sample').disabled=$('package').disabled=true;controls(false);$('download').disabled=true;$('review').checked=false;clearModel();source?.dispose();report={sourceFile:report.sourceFile,sourceSHA256:report.sourceSHA256,stage:'input-boundary',motionSamples:[]};plan=planMoc3(raw,$('parameter').value);atlas=planAtlas(plan);activeIndex=plan.activeIndex;report.support={parameter:plan.parameter,parameters:plan.parameters,mappings:plan.mappings,mapping:plan.mapping,visibleLayers:plan.meshes.length,atlasSize:atlas.size,warnings:plan.warnings};
  const freshCanvas=document.createElement('canvas');freshCanvas.id='source';$('source').replaceWith(freshCanvas);freshCanvas.width=Math.min(512,plan.width);freshCanvas.height=Math.round(freshCanvas.width*plan.height/plan.width);source=await createMeshRenderer(freshCanvas,raw);values=defaults();activeIndex=plan.activeIndex;drawSource();
  report.stage='atlas';const png=await textureAtlas();report.stage='worker-writer';const input=writerInput(plan,atlas),worker=new Worker(new URL('./moc3-worker.js?ui=5',import.meta.url),{type:'module'});const binary=await new Promise((resolve,reject)=>{const timeout=setTimeout(()=>{worker.terminate();reject(new Error('导出器超时'));},15000);worker.onmessage=event=>{clearTimeout(timeout);worker.terminate();event.data.error?reject(new Error(event.data.error.message)):resolve(event.data.binary);};worker.onerror=error=>{clearTimeout(timeout);worker.terminate();reject(new Error(error.message));};worker.postMessage(input);});
  assert(binary instanceof ArrayBuffer&&binary.byteLength>=1984&&binary.byteLength<=8*1024*1024,'导出二进制超出预算');report.mocBytes=binary.byteLength;report.mocSHA256=await sha(binary);report.stage='official-core';await loadMoc3Core();({createCubism53Viewer}=await import('../v2/cubism53-viewer.js?moc3=4'));report.core=validateCore(binary);
  const bytes=value=>encoder.encode(json(value));files=new Map([['model.moc3',new Uint8Array(binary)],['model.model3.json',bytes(modelReferences())],['textures/texture_00.png',png],['motions/test.motion3.json',bytes(testMotion(plan))]]);
  const license=await fetch('../vendor/experimental-moc3/LICENSE.MIT').then(r=>r.text());files.set('WRITER-LICENSE.txt',encoder.encode(license));report.fileHashes=Object.fromEntries(await Promise.all([...files].map(async([name,data])=>[name,await sha(data)])));await loadGenerated();$('parameter').replaceChildren(...plan.parameters.map(p=>{const option=document.createElement('option');option.value=p.id;option.textContent=p.id;return option;}));$('parameter').value=plan.parameter.id;
  }catch(error){failure(error);}finally{$('generate').disabled=false;$('project').disabled=false;$('parameter').disabled=false;$('sample').disabled=$('multi-sample').disabled=$('package').disabled=false;}};
for(const [id,next]of [['zero',0],['half',.5],['one',1]])$(id).onclick=()=>setValue(next);
$('parameter').onchange=()=>{if(!plan)return;const index=plan.parameters.findIndex(p=>p.id===$('parameter').value);if(index<0)return;activeIndex=index;setValues(defaults());};
$('combinations').onclick=async()=>{try{for(const id of ['combinations','zero','half','one','motion','parameter','generate','project','sample','multi-sample','package','review'])$(id).disabled=true;$('review').checked=false;$('download').disabled=true;for(const next of parameterSamples(plan)){setValues(next);await new Promise(resolve=>requestAnimationFrame(resolve));$('compare').click();}setValues(defaults());report.combinationsChecked=true;updateReport();}catch(error){failure(error);}finally{for(const id of ['combinations','zero','half','one','motion','parameter','generate','project','sample','multi-sample','package','review'])$(id).disabled=false;}};
$('motion').onclick=()=>{manual=false;report.motionSamples=[];report.stage='motion-playing';model.startMotion('Test',0,3);$('status').textContent='正在播放导出 model3 引用的真实测试动作。';};
$('compare').onclick=()=>{const sourceCanvas=$('source'),targetCanvas=$('target').querySelector('canvas'),read=canvas=>{const copy=document.createElement('canvas');copy.width=canvas.width;copy.height=canvas.height;const ctx=copy.getContext('2d');ctx.drawImage(canvas,0,0);return ctx.getImageData(0,0,copy.width,copy.height).data;};model.draw();drawSource();const a=read(sourceCanvas),b=read(targetCanvas);let changed=0,total=0,alphaMismatch=0,visiblePixels=0,hash=2166136261;for(let i=0;i<a.length;i+=4){let pixel=false;for(let j=0;j<4;j++){hash=Math.imul(hash^b[i+j],16777619);const delta=Math.abs(a[i+j]-b[i+j]);total+=delta;if(delta>3)pixel=true;}if(pixel)changed++;if(b[i+3]>16)visiblePixels++;if(Math.abs(a[i+3]-b[i+3])>3)alphaMismatch++;}report.pixelComparisons??=[];report.pixelComparisons.push({value:core.getParameterValueByIndex(activeIndex),values:{...values},width:sourceCanvas.width,height:sourceCanvas.height,pixels:sourceCanvas.width*sourceCanvas.height,changedPixelsAbove3:changed,alphaMismatch,visiblePixels,renderedPixelHash:(hash>>>0).toString(16),meanAbsoluteChannelError:total/a.length});updateReport();};
function acceptance(){const comparisons=report.pixelComparisons||[],same=(a,b)=>plan.parameters.every(p=>Math.abs(a?.[p.id]-b[p.id])<1e-5),expected=plan.parameters.length===1?[0,.5,1].map(v=>({...defaults(),[plan.parameter.id]:v})):parameterSamples(plan),samples=expected.map(values=>comparisons.findLast(sample=>same(sample.values,values)));const motionDistinct=new Set(report.motionSamples.map(sample=>JSON.stringify(sample.vertices))).size;
  const pixelsWithinTolerance=samples.every(sample=>sample&&sample.visiblePixels>0&&sample.meanAbsoluteChannelError<=1&&sample.changedPixelsAbove3/sample.pixels<=.03&&sample.alphaMismatch/sample.pixels<=.01),renderedEndpointMotion=!!(samples.every(Boolean)&&new Set(samples.map(s=>s.renderedPixelHash)).size>1);
  return {samplesPresent:samples.every(Boolean),pixelsWithinTolerance,renderedEndpointMotion,motionDistinct,accepted:pixelsWithinTolerance&&renderedEndpointMotion&&motionDistinct>1&&!report.error&&report.frameworkLoaded};}
$('review').onchange=()=>{report.acceptance=acceptance();$('download').disabled=!$('review').checked||!report.acceptance.accepted;if($('review').checked&&!report.acceptance.accepted)$('status').textContent='下载尚未通过：需核对独立参数组合（单参数为 0 / 0.5 / 1）且播放真实动作，画面对比不能超过容差。';updateReport();};
$('download').onclick=async()=>{try{report.acceptance=acceptance();assert(report.acceptance.accepted&&$('review').checked,'模型包验收门槛尚未满足');report.visualApproved=$('review').checked;report.stage='verified-package-download';files.set('VALIDATION.json',encoder.encode(json(report)));files.set('README.txt',encoder.encode('Experimental flat ArtMesh MOC3. One to four independent animated parameters, at most one per mesh; no rotation, hierarchy, masks, physics or complete blink/mouth/wave rig. Generated locally. Official Core is not included. Keep WRITER-LICENSE.txt.\n'));downloadBlob(zipFiles(files),'independent-parameters-moc3.zip');updateReport();}catch(error){failure(error);}};
$('package').onchange=async()=>{try{report.stage='zip-reopen';const file=$('package').files[0];const imported=await readZip(await file.arrayBuffer());const reopened=new Map(imported.files);for(const name of ['model.moc3','model.model3.json','textures/texture_00.png','motions/test.motion3.json'])assert(await sha(reopened.get(name))===report.fileHashes[name],'重新打开文件哈希不符：'+name);for(const [name,data]of reopened)files.set(name,data);report.reopenedCore=validateCore(files.get('model.moc3').buffer.slice(files.get('model.moc3').byteOffset,files.get('model.moc3').byteOffset+files.get('model.moc3').byteLength));report.zipReopenHashesMatched=true;await loadGenerated();report.stage='zip-reopened-rendered';$('status').textContent='ZIP 模型文件哈希一致，官方 Core 和渲染器重新加载成功。';updateReport();}catch(error){failure(error);}};
$('audit').onclick=()=>downloadBlob(new Blob([json({...report,current:snapshot()})],{type:'application/json'}),'validation-report.json');
addEventListener('pagehide',()=>{clearModel();source?.dispose();},{once:true});
